/* The character pools. Each entry is [name, a short note].
   Add freely — every draft shuffles the whole list into a fresh deck. */

window.UNIVERSES = {
  westeros: {
    name: "Westeros",
    blurb: "Game of Thrones and House of the Dragon",
    characters: [
      ["Jon Snow", "Lord Commander, King in the North"],
      ["Daenerys Targaryen", "Mother of Dragons"],
      ["Tyrion Lannister", "Hand of the Queen, drinks and knows things"],
      ["Cersei Lannister", "Queen of the Seven Kingdoms"],
      ["Jaime Lannister", "The Kingslayer"],
      ["Tywin Lannister", "Lord of Casterly Rock"],
      ["Arya Stark", "No one, with a list"],
      ["Sansa Stark", "Lady of Winterfell"],
      ["Bran Stark", "The Three-Eyed Raven"],
      ["Ned Stark", "Warden of the North"],
      ["Robb Stark", "The Young Wolf"],
      ["Catelyn Stark", "Lady of Riverrun"],
      ["Theon Greyjoy", "Prince of the Iron Islands, eventually"],
      ["Yara Greyjoy", "Ironborn captain"],
      ["Euron Greyjoy", "Self-styled king of the sea"],
      ["Sandor Clegane", "The Hound"],
      ["Gregor Clegane", "The Mountain"],
      ["Brienne of Tarth", "Knight of the Seven Kingdoms"],
      ["Podrick Payne", "Squire with hidden talents"],
      ["Bronn", "Ser Bronn of the Blackwater, sellsword who always backs the winner"],
      ["Samwell Tarly", "Maester-in-training"],
      ["Jorah Mormont", "Exiled knight, sworn shield"],
      ["Davos Seaworth", "The Onion Knight"],
      ["Stannis Baratheon", "The one true king, by his reckoning"],
      ["Robert Baratheon", "King, warhammer, appetite"],
      ["Joffrey Baratheon", "Boy king"],
      ["Melisandre", "The Red Woman"],
      ["Petyr Baelish", "Littlefinger"],
      ["Varys", "The Spider"],
      ["Oberyn Martell", "The Red Viper"],
      ["Ellaria Sand", "Paramour of Dorne"],
      ["Tormund Giantsbane", "Free folk raider"],
      ["Ygritte", "Free folk archer"],
      ["The Night King", "Leader of the White Walkers"],
      ["Khal Drogo", "Undefeated horselord"],
      ["Grey Worm", "Commander of the Unsullied"],
      ["Missandei", "Translator and advisor"],
      ["Margaery Tyrell", "Rose of Highgarden"],
      ["Olenna Tyrell", "The Queen of Thorns"],
      ["Ramsay Bolton", "Bastard of the Dreadfort"],
      ["Jaqen H'ghar", "A man of the Faceless"],
      ["Gendry", "Blacksmith with a royal secret"],
      ["Hodor", "Holds the door"],
      ["Beric Dondarrion", "Lord of the flaming sword"],
      ["Barristan Selmy", "Barristan the Bold"],
      ["Daario Naharis", "Second Sons captain"],
      ["Rhaenyra Targaryen", "The Black Queen"],
      ["Daemon Targaryen", "Rogue Prince"],
      ["Viserys I Targaryen", "The Peaceful King"],
      ["Alicent Hightower", "The Green Queen"],
      ["Otto Hightower", "Hand of two kings"],
      ["Aegon II Targaryen", "The Green King"],
      ["Aemond Targaryen", "One-eyed rider of Vhagar"],
      ["Helaena Targaryen", "Dreamer of the Greens"],
      ["Criston Cole", "Lord Commander of the Kingsguard"],
      ["Corlys Velaryon", "The Sea Snake"],
      ["Rhaenys Targaryen", "The Queen Who Never Was"],
      ["Jacaerys Velaryon", "Heir to Dragonstone"],
      ["Baela Targaryen", "Rider of Moondancer"],
      ["Larys Strong", "Clubfoot, keeper of secrets"],
      ["Mysaria", "The White Worm"],
      ["Cregan Stark", "Lord of Winterfell, Dance era"],
      ["Alys Rivers", "Witch of Harrenhal"],
      ["Drogon", "Dragon, black and red"],
      ["Rhaegal", "Dragon, green and bronze"],
      ["Viserion", "Dragon, later ice"],
      ["Vhagar", "Oldest and largest living dragon"],
      ["Caraxes", "The Blood Wyrm"],
      ["Meleys", "The Red Queen"],
      ["Sunfyre", "The Golden"],
      ["Ghost", "Silent white direwolf"],
      ["Nymeria", "Direwolf, leader of the pack"],
    ],
    // Known for strategy, leadership or cunning; the judge weighs this.
    // Battlefields: [name, terrain for the judge, picture]. One is drawn when the battle begins.
    arenas: [
      ["The Wall", "A seven-hundred-foot cliff of ice with Castle Black at its foot, a single tunnel gate, lifts and stairs up the face, and frozen forest beyond. Brutal cold; the high ground is everything.", "https://static.wikia.nocookie.net/gameofthrones/images/7/7b/Castle_Black.jpg/revision/latest/scale-to-width-down/800?cb=20110920111941"],
      ["Highgarden", "Golden fields and orchards around a castle of concentric walls on the River Mander. Open ground for cavalry, hedge mazes for ambushes, granaries worth burning.", "https://static.wikia.nocookie.net/gameofthrones/images/a/a2/704_Highgarden.png/revision/latest/scale-to-width-down/800?cb=20170807030944"],
      ["King's Landing", "Narrow, crowded streets climbing three hills to the Red Keep, with secret tunnels beneath, caches of wildfire, and Blackwater Bay at its feet.", "https://static.wikia.nocookie.net/gameofthrones/images/8/83/King%27s_Landing_HotD.png/revision/latest/scale-to-width-down/800?cb=20220805155800"],
      ["Winterfell", "A great castle of double walls and a moat in deep snow, with the crypts below, the godswood within, and hot springs keeping the keep warm.", "https://static.wikia.nocookie.net/gameofthrones/images/1/1f/801_Winterfell_Overview.png/revision/latest/scale-to-width-down/800?cb=20190415031728"],
      ["Harrenhal", "A vast, half-melted ruin of five towers, mostly empty and said to be cursed. Endless corridors to hide in, walls too big to defend.", "https://static.wikia.nocookie.net/gameofthrones/images/9/9b/Harrenhal.jpg/revision/latest/scale-to-width-down/800?cb=20150328214605"],
      ["Dragonstone", "A volcanic island fortress carved like dragons, ringed by sea cliffs, with a hidden mine of dragonglass beneath it.", "https://static.wikia.nocookie.net/gameofthrones/images/a/a4/Dragonstone-season7-low.png/revision/latest/scale-to-width-down/800?cb=20170717082952"],
      ["The Eyrie", "A castle on a mountain peak, reached by one narrow, deadly path. The Moon Door opens onto a sheer drop. Impregnable, if you're already inside.", "https://static.wikia.nocookie.net/gameofthrones/images/5/59/The_Eyrie.jpg/revision/latest/scale-to-width-down/800?cb=20110615190250"],
      ["Meereen", "A city of stepped pyramids above the Slaver's Bay docks, with Daznak's fighting pit at its heart and plenty of people with knives in the alleys.", "https://static.wikia.nocookie.net/gameofthrones/images/8/89/Meereen.png/revision/latest/scale-to-width-down/800?cb=20150328211743"],
    ],
    strategists: ["Tywin Lannister", "Tyrion Lannister", "Stannis Baratheon", "Robb Stark", "Petyr Baelish", "Varys", "Olenna Tyrell", "Cersei Lannister", "Bronn", "Davos Seaworth", "Sansa Stark", "Bran Stark", "Jaime Lannister", "Ramsay Bolton", "Euron Greyjoy", "The Night King", "Grey Worm", "Barristan Selmy", "Margaery Tyrell", "Jaqen H'ghar", "Daemon Targaryen", "Otto Hightower", "Larys Strong", "Corlys Velaryon", "Criston Cole", "Aemond Targaryen", "Cregan Stark", "Mysaria", "Rhaenys Targaryen"],
  },

  marvel: {
    name: "Marvel",
    blurb: "Avengers, X-Men, villains and deep cuts",
    characters: [
      ["Iron Man", "Genius in a suit of armour"],
      ["Captain America", "Super-soldier with a shield"],
      ["Thor", "God of Thunder"],
      ["Hulk", "Smash, mostly"],
      ["Black Widow", "Master spy"],
      ["Hawkeye", "Never misses"],
      ["Spider-Man", "Friendly neighbourhood wall-crawler"],
      ["Doctor Strange", "Sorcerer Supreme"],
      ["Black Panther", "King of Wakanda"],
      ["Captain Marvel", "Cosmic-powered pilot"],
      ["Scarlet Witch", "Reality-bending chaos magic"],
      ["Vision", "Synthezoid with a mind stone"],
      ["Ant-Man", "Shrinks, grows, quips"],
      ["The Wasp", "Small, fast, stings"],
      ["Falcon", "Winged sky soldier"],
      ["Winter Soldier", "Metal arm, long memory"],
      ["War Machine", "Heavily armed armour"],
      ["Star-Lord", "Legendary outlaw, self-declared"],
      ["Gamora", "Deadliest woman in the galaxy"],
      ["Drax", "The Destroyer"],
      ["Rocket", "Raccoon with heavy weapons"],
      ["Groot", "He is Groot"],
      ["Mantis", "Empath"],
      ["Nebula", "Cyborg assassin"],
      ["Thanos", "The Mad Titan"],
      ["Loki", "God of Mischief"],
      ["Ultron", "Rogue AI"],
      ["Hela", "Goddess of Death"],
      ["Wolverine", "Claws and a healing factor"],
      ["Deadpool", "Merc with a mouth"],
      ["Professor X", "Most powerful telepath"],
      ["Magneto", "Master of magnetism"],
      ["Storm", "Commands the weather"],
      ["Phoenix", "Jean Grey, cosmic fire"],
      ["Cyclops", "Optic blasts, field leader"],
      ["Rogue", "Absorbs powers by touch"],
      ["Gambit", "Charged playing cards"],
      ["Mystique", "Shapeshifter"],
      ["Juggernaut", "Nothing stops him"],
      ["Nightcrawler", "Teleporting acrobat"],
      ["Silver Surfer", "Herald of Galactus"],
      ["Galactus", "Devourer of worlds"],
      ["Doctor Doom", "Monarch of Latveria"],
      ["Mister Fantastic", "Stretchy genius"],
      ["Invisible Woman", "Force fields and invisibility"],
      ["Human Torch", "Flame on"],
      ["The Thing", "Rocky, ever-loving"],
      ["Ghost Rider", "Spirit of Vengeance"],
      ["Daredevil", "The Man Without Fear"],
      ["The Punisher", "Vigilante with an arsenal"],
      ["Moon Knight", "Fist of Khonshu"],
      ["Blade", "Daywalker vampire hunter"],
      ["Ms. Marvel", "Embiggening teen hero"],
      ["She-Hulk", "Lawyer, also enormous"],
      ["Shang-Chi", "Master of the ten rings"],
      ["Venom", "Symbiote, very hungry"],
      ["Carnage", "Symbiote, very unhinged"],
      ["Green Goblin", "Glider and pumpkin bombs"],
      ["Doctor Octopus", "Four extra arms"],
      ["Kang the Conqueror", "Time-travelling tyrant"],
      ["Red Skull", "Leader of Hydra"],
      ["Namor", "King of Atlantis"],
      ["Adam Warlock", "Cosmic golden being"],
      ["Nick Fury", "Director of S.H.I.E.L.D."],
      ["Kingpin", "Crime boss of New York"],
      ["Black Bolt", "One whisper levels a city"],
      ["Okoye", "General of the Dora Milaje"],
      ["Valkyrie", "Asgardian warrior"],
      ["Squirrel Girl", "Unbeatable, apparently"],
      ["Howard the Duck", "Trapped in a world he never made"],
      ["Bullseye", "Turns anything into a weapon"],
      ["Elektra", "Assassin with twin sai"],
      ["Iron Fist", "Immortal Weapon of K'un-Lun"],
      ["Luke Cage", "Unbreakable hero for hire"],
      ["Jessica Jones", "Super-strong private eye"],
      ["Misty Knight", "Detective with a bionic arm"],
      ["Cloak", "Living portal of darkness"],
      ["Dagger", "Throws knives of pure light"],
      ["Morbius", "The Living Vampire"],
      ["Kraven the Hunter", "Hunts the most dangerous game"],
      ["Mysterio", "Master of illusions"],
      ["Vulture", "Winged scavenger"],
      ["Rhino", "Charges first, thinks later"],
      ["Scorpion", "Armoured tail, short temper"],
      ["Electro", "Living lightning"],
      ["Taskmaster", "Copies any move he sees"],
      ["Crossbones", "Hydra brawler"],
      ["Baron Zemo", "Sokovian schemer in purple"],
      ["Arnim Zola", "Mind uploaded to a computer"],
      ["MODOK", "Mostly head, entirely ego"],
      ["Ego", "A living planet"],
      ["Yondu", "Whistle-guided arrow"],
      ["Cosmo", "Telepathic space dog"],
      ["Beta Ray Bill", "Worthy of his own hammer"],
      ["Gorr", "The God Butcher"],
      ["Black Knight", "Wields the cursed Ebony Blade"],
      ["Hercules", "The Prince of Power"],
      ["America Chavez", "Punches holes between universes"],
      ["Kate Bishop", "The other Hawkeye"],
      ["Echo", "Copies any fighting style"],
      ["Jubilee", "Fireworks from her fingertips"],
      ["Colossus", "Organic steel"],
      ["Kitty Pryde", "Walks through walls"],
      ["Iceman", "Freezes anything"],
      ["Beast", "Blue, furry and brilliant"],
      ["Psylocke", "Psychic blades"],
      ["Cable", "Time-travelling soldier from the future"],
      ["Domino", "Luck as a superpower"],
      ["Emma Frost", "The White Queen, diamond form"],
      ["Apocalypse", "The first mutant"],
      ["Sabretooth", "Wolverine's oldest enemy"],
      ["Sentry", "Power of a million exploding suns"],
      ["Wonder Man", "Ionic powerhouse, part-time actor"],
      ["Hellcat", "Talk show host turned hero"],
      ["Werewolf by Night", "Monster hunter, sometimes the monster"],
      ["Man-Thing", "Whoever knows fear burns at his touch"],
      ["Mephisto", "Ruler of a hell"],
      ["Dormammu", "Lord of the Dark Dimension"],
      ["Knull", "God of the symbiotes"],
      ["Ghost", "Phases in and out of reality"],
      ["Abomination", "Hulk's scaly rival"],
      ["The Leader", "Gamma-powered super-genius"],
      ["Wong", "Sorcerer Supreme, eventually"],
      ["Agatha Harkness", "Witch of Westview"],
      ["Killmonger", "Challenger for the throne of Wakanda"],
      ["M'Baku", "Leader of the Jabari"],
      ["Shuri", "Wakanda's genius, later Black Panther"],
      ["Nova", "Human Rocket of the Nova Corps"],
      ["Ronan the Accuser", "Kree zealot with a hammer"],
      ["Grandmaster", "Runs the contest of champions"],
      ["The Collector", "Keeper of rare things"],
      ["Batroc the Leaper", "French kickboxing mercenary"],
      ["Doop", "Floating green blob, surprisingly deadly"],
      ["Throg", "Thor, but a frog"],
      ["Lockjaw", "Teleporting Inhuman bulldog"],
      ["Jeff the Land Shark", "Tiny shark, huge fanbase"],
      ["Tigra", "Were-woman with claws"],
      ["Bob, Agent of Hydra", "Hydra henchman, Deadpool's pal"],
      ["Moon Girl", "Smartest kid alive, has a dinosaur"],
      ["Forge", "Mutant inventor"],
      ["Union Jack", "Britain's masked patriot"],
      ["Stick", "Blind master of the Chaste"],
      ["Ikaris", "Eternal with laser eyes"],
      ["Thena", "Eternal warrior goddess"],
      ["Kingo", "Eternal and film star"],
      ["Leech", "Shuts off powers nearby"],
    ],
    // Known for strategy, leadership or cunning; the judge weighs this.
    // Battlefields: [name, terrain for the judge, picture]. One is drawn when the battle begins.
    arenas: [
      ["Wakanda", "The Golden City of Birnin Zana, with vibranium tech, maglev trains and force-field defences, plus the cliffs of Warrior Falls and dense jungle at its edge.", "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/5/58/Golden_city_wakanda.png/revision/latest/scale-to-width-down/800?cb=20221112021631"],
      ["Asgard", "A floating realm of golden palaces, the rainbow Bifrost bridge and the edge of the world, where falling means falling forever.", "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/2/26/AsgardFull.jpg/revision/latest/scale-to-width-down/800?cb=20220709021326"],
      ["New York City", "Skyscrapers, crowded avenues, subway tunnels and rooftops. Plenty of cover, plenty of bystanders, and police on the way.", "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/f/f5/City_that_never_sleeps.png/revision/latest/scale-to-width-down/800?cb=20250416223202"],
      ["Knowhere", "A mining colony built inside the severed head of a Celestial: dark, lawless, cramped tunnels and a Collector's museum full of oddities.", "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/d/d9/Knowhere_-_movie.png/revision/latest/scale-to-width-down/800?cb=20260203235948"],
      ["Sakaar", "A junk planet ringed by wormholes, ruled by the Grandmaster, with a gladiatorial arena, scrap heaps and anything-goes spaceships.", "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/d/d5/Sakaar.png/revision/latest/scale-to-width-down/800?cb=20180419174030"],
      ["Titan", "Thanos's ruined homeworld: broken spires, wrecked moons hanging in the sky and scattered debris that can become a weapon.", "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/5/54/AW_1_Trailer_pic.png/revision/latest/scale-to-width-down/800?cb=20220205173457"],
      ["Kamar-Taj", "A mountain temple of the mystic arts in Nepal, with libraries of spells, portals to anywhere and sorcerers who don't like intruders.", "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/2/2e/Doctor_Strange_Final_Trailer_07.png/revision/latest/scale-to-width-down/800?cb=20211016142921"],
      ["Avengers Compound", "Wide fields, a lake and a high-tech base upstate, with hangars, labs and plenty of room for an all-out war.", "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/2/20/AvengersEndgame_06.png/revision/latest/scale-to-width-down/800?cb=20190326194352"],
    ],
    strategists: ["Captain America", "Nick Fury", "Professor X", "Magneto", "Doctor Doom", "Mister Fantastic", "Black Widow", "Thanos", "Loki", "Kang the Conqueror", "Red Skull", "Kingpin", "Cyclops", "Black Panther", "Taskmaster", "Baron Zemo", "Cable", "Okoye", "Storm", "Emma Frost", "Mystique", "Iron Man", "Doctor Strange", "Ultron", "Apocalypse", "Killmonger", "The Punisher", "Rocket", "Arnim Zola", "The Leader", "MODOK", "Daredevil", "Kitty Pryde", "Agatha Harkness", "Mephisto", "Grandmaster", "Domino", "Bullseye", "Elektra"],
  },

  league: {
    name: "League of Legends",
    blurb: "Champions from across Runeterra",
    characters: [
      ["Ahri", "Ionia · nine-tailed fox mage"],
      ["Yasuo", "Ionia · the Unforgiven"],
      ["Yone", "Ionia · the Unforgotten"],
      ["Lee Sin", "Ionia · the Blind Monk"],
      ["Master Yi", "Ionia · the Wuju Bladesman"],
      ["Irelia", "Ionia · the Blade Dancer"],
      ["Akali", "Ionia · the Rogue Assassin"],
      ["Shen", "Ionia · Eye of Twilight"],
      ["Zed", "Ionia · Master of Shadows"],
      ["Kennen", "Ionia · Heart of the Tempest"],
      ["Jinx", "Zaun · the Loose Cannon"],
      ["Vi", "Piltover · the Piltover Enforcer"],
      ["Caitlyn", "Piltover · the Sheriff"],
      ["Jayce", "Piltover · Defender of Tomorrow"],
      ["Viktor", "Zaun · the Machine Herald"],
      ["Ekko", "Zaun · the Boy Who Shattered Time"],
      ["Ezreal", "Piltover · the Prodigal Explorer"],
      ["Heimerdinger", "Piltover · the Revered Inventor"],
      ["Singed", "Zaun · the Mad Chemist"],
      ["Warwick", "Zaun · the Uncaged Wrath"],
      ["Lux", "Demacia · the Lady of Luminosity"],
      ["Garen", "Demacia · the Might of Demacia"],
      ["Jarvan IV", "Demacia · the Exemplar"],
      ["Xin Zhao", "Demacia · the Seneschal"],
      ["Sylas", "Demacia · the Unshackled"],
      ["Darius", "Noxus · the Hand of Noxus"],
      ["Draven", "Noxus · the Glorious Executioner"],
      ["Katarina", "Noxus · the Sinister Blade"],
      ["Swain", "Noxus · the Noxian Grand General"],
      ["LeBlanc", "Noxus · the Deceiver"],
      ["Sion", "Noxus · the Undead Juggernaut"],
      ["Ashe", "Freljord · the Frost Archer"],
      ["Sejuani", "Freljord · Fury of the North"],
      ["Lissandra", "Freljord · the Ice Witch"],
      ["Braum", "Freljord · the Heart of the Freljord"],
      ["Tryndamere", "Freljord · the Barbarian King"],
      ["Ornn", "Freljord · the Fire below the Mountain"],
      ["Volibear", "Freljord · the Relentless Storm"],
      ["Anivia", "Freljord · the Cryophoenix"],
      ["Leona", "Targon · the Radiant Dawn"],
      ["Diana", "Targon · Scorn of the Moon"],
      ["Pantheon", "Targon · the Unbreakable Spear"],
      ["Aphelios", "Targon · the Weapon of the Faithful"],
      ["Aurelion Sol", "Targon · the Star Forger"],
      ["Miss Fortune", "Bilgewater · the Bounty Hunter"],
      ["Gangplank", "Bilgewater · the Saltwater Scourge"],
      ["Graves", "Bilgewater · the Outlaw"],
      ["Twisted Fate", "Bilgewater · the Card Master"],
      ["Pyke", "Bilgewater · the Bloodharbor Ripper"],
      ["Thresh", "Shadow Isles · the Chain Warden"],
      ["Viego", "Shadow Isles · the Ruined King"],
      ["Senna", "the Redeemer"],
      ["Lucian", "the Purifier"],
      ["Azir", "Shurima · the Emperor of the Sands"],
      ["Nasus", "Shurima · the Curator of the Sands"],
      ["Renekton", "Shurima · the Butcher of the Sands"],
      ["Xerath", "Shurima · the Magus Ascendant"],
      ["Rammus", "Shurima · the Armordillo"],
      ["Aatrox", "Runeterra · the Darkin Blade"],
      ["Kayle", "Demacia · the Righteous"],
      ["Morgana", "Demacia · the Fallen"],
      ["Mordekaiser", "Shadow Isles · the Iron Revenant"],
      ["Kai'Sa", "Void · Daughter of the Void"],
      ["Vel'Koz", "Void · the Eye of the Void"],
      ["Bard", "the Wandering Caretaker"],
      ["Nocturne", "the Eternal Nightmare"],
      ["Fiddlesticks", "the Ancient Fear"],
      ["Sett", "Ionia · the Boss"],
      ["Teemo", "Bandle City · the Swift Scout"],
      ["Yuumi", "Bandle City · the Magical Cat"],
      ["Annie", "Noxus · the Dark Child"],
      ["Blitzcrank", "Zaun · the Great Steam Golem"],
      ["Malphite", "Ixtal · Shard of the Monolith"],
      ["Gwen", "Shadow Isles · the Hallowed Seamstress"],
    ],
    // Known for strategy, leadership or cunning; the judge weighs this.
    // Battlefields: [name, terrain for the judge, picture]. One is drawn when the battle begins.
    arenas: [
      ["Summoner's Rift", "Three lanes guarded by towers, a jungle full of monsters and a river between, with Baron Nashor's pit and the Dragon's lair to fight over.", "https://static.wikia.nocookie.net/leagueoflegends/images/3/3e/Summoner%27s_Rift_Intro_Art.jpg/revision/latest?cb=20110922005730"],
      ["Howling Abyss", "A single narrow bridge of ice and stone over a bottomless chasm in the Freljord. Nowhere to hide and nowhere to run, only forward.", "https://static.wikia.nocookie.net/leagueoflegends/images/b/b5/Howling_Abyss_Landscape.png/revision/latest/scale-to-width-down/800?cb=20170303155408"],
      ["Piltover", "The City of Progress: gleaming towers, hextech gadgets, the Hexgates on the sea cliffs and an Enforcer on every corner.", "https://static.wikia.nocookie.net/leagueoflegends/images/8/83/Piltover_Arcane_01.jpg/revision/latest/scale-to-width-down/800?cb=20220203165523"],
      ["Zaun", "The undercity below Piltover, choked with chem-fumes, shimmer labs, chem-barons' gangs and a maze of pipes and lifts.", "https://static.wikia.nocookie.net/leagueoflegends/images/6/66/Zaun_Arcane_01.jpg/revision/latest/scale-to-width-down/800?cb=20220203174607"],
      ["Bilgewater", "A lawless port of rickety docks, pirate ships, sea serpent hunters and bounty boards, where everyone can be bought.", "https://static.wikia.nocookie.net/leagueoflegends/images/a/a3/Bilgewater_Bilgewater_Bay_01.jpg/revision/latest/scale-to-width-down/800?cb=20190807010828"],
      ["Shurima", "An endless desert around a risen golden city and its Sun Disc, with buried tombs, sandstorms and ancient ascended power.", "https://static.wikia.nocookie.net/leagueoflegends/images/4/4e/Shurima_Atop_The_Dormun_01.jpg/revision/latest/scale-to-width-down/800?cb=20180917152707"],
      ["Shadow Isles", "Islands smothered in the Black Mist, where the dead don't stay dead and the living slowly lose themselves.", "https://static.wikia.nocookie.net/leagueoflegends/images/6/6f/Shadow_Isles_Beyond_The_Isles.jpg/revision/latest/scale-to-width-down/800?cb=20190126160819"],
      ["Mount Targon", "The tallest mountain in Runeterra, a deadly climb to a summit where celestial powers choose their champions.", "https://static.wikia.nocookie.net/leagueoflegends/images/f/f4/Targon_Around_The_Mountain.jpg/revision/latest/scale-to-width-down/800?cb=20180515050333"],
    ],
    strategists: ["Swain", "Jarvan IV", "Azir", "Darius", "LeBlanc", "Twisted Fate", "Gangplank", "Miss Fortune", "Sejuani", "Ashe", "Lissandra", "Caitlyn", "Heimerdinger", "Viktor", "Ekko", "Zed", "Shen", "Pyke", "Thresh", "Xerath", "Nasus", "Mordekaiser", "Xin Zhao", "Garen", "Bard", "Graves", "Sylas", "Jayce", "Viego"],
  },
};
