/* Character pictures, keyed by world then name. Generated from the Game of Thrones
   and Marvel Fandom wikis and Riot's Data Dragon. A character with no entry here
   gets a lettered placeholder instead, so new characters can be added freely. */

window.CHARACTER_IMAGES = {
  "westeros": {
    "Jon Snow": "https://static.wikia.nocookie.net/gameofthrones/images/d/d0/JonSnow8x06.PNG/revision/latest/scale-to-width-down/400",
    "Daenerys Targaryen": "https://static.wikia.nocookie.net/gameofthrones/images/4/4f/Daenerys_Season_8.jpg/revision/latest/scale-to-width-down/400",
    "Tyrion Lannister": "https://static.wikia.nocookie.net/gameofthrones/images/9/95/HandoftheKingTyrionLannister.PNG/revision/latest/scale-to-width-down/400",
    "Cersei Lannister": "https://static.wikia.nocookie.net/gameofthrones/images/b/b0/CERSEIBATTLEOFKINGSLANDING.PNG/revision/latest/scale-to-width-down/400",
    "Jaime Lannister": "https://static.wikia.nocookie.net/gameofthrones/images/5/51/JaimeLannisterSeason8.PNG/revision/latest/scale-to-width-down/400",
    "Tywin Lannister": "https://static.wikia.nocookie.net/gameofthrones/images/7/71/Tywin_Lannister_4x08.jpg/revision/latest/scale-to-width-down/400",
    "Arya Stark": "https://static.wikia.nocookie.net/gameofthrones/images/b/be/AryaShipIronThrone.PNG/revision/latest/scale-to-width-down/400",
    "Sansa Stark": "https://static.wikia.nocookie.net/gameofthrones/images/6/63/QueenSansa.PNG/revision/latest/scale-to-width-down/400",
    "Bran Stark": "https://static.wikia.nocookie.net/gameofthrones/images/8/81/KingBran.PNG/revision/latest/scale-to-width-down/400",
    "Ned Stark": "https://static.wikia.nocookie.net/gameofthrones/images/3/34/Eddard_Stark.jpg/revision/latest/scale-to-width-down/400",
    "Robb Stark": "https://static.wikia.nocookie.net/gameofthrones/images/5/50/S3E9_Robb_Stark_main.jpg/revision/latest/scale-to-width-down/400",
    "Catelyn Stark": "https://static.wikia.nocookie.net/gameofthrones/images/d/d8/CatelynS3Promo.jpg/revision/latest/scale-to-width-down/400",
    "Theon Greyjoy": "https://static.wikia.nocookie.net/gameofthrones/images/7/78/TheonS8E1.PNG/revision/latest/scale-to-width-down/400",
    "Yara Greyjoy": "https://static.wikia.nocookie.net/gameofthrones/images/a/a8/Game_of_thrones_6x5_yara_promo.jpg/revision/latest/scale-to-width-down/400",
    "Euron Greyjoy": "https://static.wikia.nocookie.net/gameofthrones/images/f/fc/Euron-Profile.PNG/revision/latest/scale-to-width-down/400",
    "Sandor Clegane": "https://static.wikia.nocookie.net/gameofthrones/images/b/b5/SandorConfrontsGregor.PNG/revision/latest/scale-to-width-down/400",
    "Gregor Clegane": "https://static.wikia.nocookie.net/gameofthrones/images/8/81/GregorGregorLightenedProfile.png/revision/latest/scale-to-width-down/400",
    "Brienne of Tarth": "https://static.wikia.nocookie.net/gameofthrones/images/a/a9/S8_Brienne_Profil.jpg/revision/latest/scale-to-width-down/400",
    "Podrick Payne": "https://static.wikia.nocookie.net/gameofthrones/images/2/22/Podrick8x01.PNG/revision/latest/scale-to-width-down/400",
    "Bronn": "https://static.wikia.nocookie.net/gameofthrones/images/f/f5/Bronn_S8E6.png/revision/latest/scale-to-width-down/400",
    "Samwell Tarly": "https://static.wikia.nocookie.net/gameofthrones/images/8/8f/Maester_Sam.png/revision/latest/scale-to-width-down/400",
    "Jorah Mormont": "https://static.wikia.nocookie.net/gameofthrones/images/2/26/Winterfell_ep_Jorah_s8.jpg/revision/latest/scale-to-width-down/400",
    "Davos Seaworth": "https://static.wikia.nocookie.net/gameofthrones/images/9/9d/DAVOSINFOBOXBELLS.PNG/revision/latest/scale-to-width-down/400",
    "Stannis Baratheon": "https://static.wikia.nocookie.net/gameofthrones/images/2/2f/StannisNew.png/revision/latest/scale-to-width-down/400",
    "Robert Baratheon": "https://static.wikia.nocookie.net/gameofthrones/images/4/43/Robert_crop.png/revision/latest/scale-to-width-down/400",
    "Joffrey Baratheon": "https://static.wikia.nocookie.net/gameofthrones/images/2/25/Joffrey_Season_4_Episode_2_TLATR.jpg/revision/latest/scale-to-width-down/400",
    "Melisandre": "https://static.wikia.nocookie.net/gameofthrones/images/0/07/Melisandre_%28The_Queen%27s_Justice%29.png/revision/latest/scale-to-width-down/400",
    "Petyr Baelish": "https://static.wikia.nocookie.net/gameofthrones/images/9/9f/Profile-Littlefinger.png/revision/latest/scale-to-width-down/400",
    "Varys": "https://static.wikia.nocookie.net/gameofthrones/images/f/ff/Varys8x05Dragonstone.PNG/revision/latest/scale-to-width-down/400",
    "Oberyn Martell": "https://static.wikia.nocookie.net/gameofthrones/images/4/44/Oberyn-Martell-house-martell_s3.jpg/revision/latest/scale-to-width-down/400",
    "Ellaria Sand": "https://static.wikia.nocookie.net/gameofthrones/images/4/4c/Ellaria_Sand_The_End.png/revision/latest/scale-to-width-down/400",
    "Tormund Giantsbane": "https://static.wikia.nocookie.net/gameofthrones/images/9/97/Tormund_Profile.PNG/revision/latest/scale-to-width-down/400",
    "Ygritte": "https://static.wikia.nocookie.net/gameofthrones/images/2/28/Ygritte-promotionals4pic.jpg/revision/latest/scale-to-width-down/400",
    "The Night King": "https://static.wikia.nocookie.net/gameofthrones/images/1/1f/Night_King_BTW.jpg/revision/latest/scale-to-width-down/400",
    "Khal Drogo": "https://static.wikia.nocookie.net/gameofthrones/images/2/21/Khal_Drogo_infobox_promo.jpg/revision/latest/scale-to-width-down/400",
    "Grey Worm": "https://static.wikia.nocookie.net/gameofthrones/images/7/77/Grey-Worm-S8E5.png/revision/latest/scale-to-width-down/400",
    "Missandei": "https://static.wikia.nocookie.net/gameofthrones/images/d/de/Missandei8X04.PNG/revision/latest/scale-to-width-down/400",
    "Margaery Tyrell": "https://static.wikia.nocookie.net/gameofthrones/images/b/b5/Margaery_Tyrell_S6.png/revision/latest/scale-to-width-down/400",
    "Olenna Tyrell": "https://static.wikia.nocookie.net/gameofthrones/images/f/f2/OlennaS7E3.png/revision/latest/scale-to-width-down/400",
    "Ramsay Bolton": "https://static.wikia.nocookie.net/gameofthrones/images/d/d2/Ramsay_S06E09_RESZIED_FOR_INFOBOX.jpg/revision/latest/scale-to-width-down/400",
    "Jaqen H'ghar": "https://static.wikia.nocookie.net/gameofthrones/images/d/da/The_Door_Jaqen_infobox.jpg/revision/latest/scale-to-width-down/400",
    "Gendry": "https://static.wikia.nocookie.net/gameofthrones/images/7/7b/GendryBaratheon.png/revision/latest/scale-to-width-down/400",
    "Hodor": "https://static.wikia.nocookie.net/gameofthrones/images/1/18/Season_6_hodor_main.jpg/revision/latest/scale-to-width-down/400",
    "Beric Dondarrion": "https://static.wikia.nocookie.net/gameofthrones/images/4/44/803_Beric_Promo_Crop.png/revision/latest/scale-to-width-down/400",
    "Barristan Selmy": "https://static.wikia.nocookie.net/gameofthrones/images/1/1f/Barristan_Selmy_Sons_of_the_Harpy.jpg/revision/latest/scale-to-width-down/400",
    "Daario Naharis": "https://static.wikia.nocookie.net/gameofthrones/images/d/d8/Daario-s6e4.jpg/revision/latest/scale-to-width-down/400",
    "Rhaenyra Targaryen": "https://static.wikia.nocookie.net/gameofthrones/images/4/40/Rhaenyra_308.png/revision/latest/scale-to-width-down/400",
    "Daemon Targaryen": "https://static.wikia.nocookie.net/gameofthrones/images/d/d5/Daemon_S3_Profile.png/revision/latest/scale-to-width-down/400",
    "Viserys I Targaryen": "https://static.wikia.nocookie.net/gameofthrones/images/3/38/Viserys_I_Targaryen_Official_Guide.jpg/revision/latest/scale-to-width-down/400",
    "Alicent Hightower": "https://static.wikia.nocookie.net/gameofthrones/images/1/18/AlicentASfASInfobox.PNG/revision/latest/scale-to-width-down/400",
    "Otto Hightower": "https://static.wikia.nocookie.net/gameofthrones/images/b/b8/Otto_Hightower-302.jpg/revision/latest/scale-to-width-down/400",
    "Aegon II Targaryen": "https://static.wikia.nocookie.net/gameofthrones/images/d/da/Aegon_302_Profile.jpg/revision/latest/scale-to-width-down/400",
    "Aemond Targaryen": "https://static.wikia.nocookie.net/gameofthrones/images/6/63/Aemond_Targaryen-301.jpg/revision/latest/scale-to-width-down/400",
    "Helaena Targaryen": "https://static.wikia.nocookie.net/gameofthrones/images/c/c8/Helaena_Targaryen-301.jpg/revision/latest/scale-to-width-down/400",
    "Criston Cole": "https://static.wikia.nocookie.net/gameofthrones/images/b/b6/Criston_Cole-306.jpg/revision/latest/scale-to-width-down/400",
    "Corlys Velaryon": "https://static.wikia.nocookie.net/gameofthrones/images/5/5a/Corlys_Velaryon_S2.jpg/revision/latest/scale-to-width-down/400",
    "Rhaenys Targaryen": "https://static.wikia.nocookie.net/gameofthrones/images/2/21/Rhaenys_Targaryen1.png/revision/latest/scale-to-width-down/400",
    "Jacaerys Velaryon": "https://static.wikia.nocookie.net/gameofthrones/images/5/5f/Jacaerys-206.jpeg/revision/latest/scale-to-width-down/400",
    "Baela Targaryen": "https://static.wikia.nocookie.net/gameofthrones/images/8/8d/BaelaTargaryen2x03.PNG/revision/latest/scale-to-width-down/400",
    "Larys Strong": "https://static.wikia.nocookie.net/gameofthrones/images/7/76/Larys_Strong_S2.jpg/revision/latest/scale-to-width-down/400",
    "Mysaria": "https://static.wikia.nocookie.net/gameofthrones/images/7/78/305_Mysaria_Still.jpg/revision/latest/scale-to-width-down/400",
    "Cregan Stark": "https://static.wikia.nocookie.net/gameofthrones/images/8/83/Cregan-portrait.png/revision/latest/scale-to-width-down/400",
    "Alys Rivers": "https://static.wikia.nocookie.net/gameofthrones/images/4/42/Alys_Rivers-304.jpg/revision/latest/scale-to-width-down/400",
    "Drogon": "https://static.wikia.nocookie.net/gameofthrones/images/8/8f/DrogonWinterfell8x01.PNG/revision/latest/scale-to-width-down/400",
    "Rhaegal": "https://static.wikia.nocookie.net/gameofthrones/images/5/54/RhaegalPostFlight.PNG/revision/latest/scale-to-width-down/400",
    "Viserion": "https://static.wikia.nocookie.net/gameofthrones/images/0/0e/Viserion_Dragonstone.png/revision/latest/scale-to-width-down/400",
    "Vhagar": "https://static.wikia.nocookie.net/gameofthrones/images/e/ef/Vhagar-302.jpg/revision/latest/scale-to-width-down/400",
    "Caraxes": "https://static.wikia.nocookie.net/gameofthrones/images/0/0e/Caraxes_Official_Guide.png/revision/latest/scale-to-width-down/400",
    "Meleys": "https://static.wikia.nocookie.net/gameofthrones/images/d/d8/Meleys-204.jpg/revision/latest/scale-to-width-down/400",
    "Sunfyre": "https://static.wikia.nocookie.net/gameofthrones/images/e/e0/Sunfyre_307.png/revision/latest/scale-to-width-down/400",
    "Ghost": "https://static.wikia.nocookie.net/gameofthrones/images/9/94/804_Ghost_Profile.png/revision/latest/scale-to-width-down/400",
    "Nymeria": "https://static.wikia.nocookie.net/gameofthrones/images/5/54/Nymeria-S7.png/revision/latest/scale-to-width-down/400"
  },
  "marvel": {
    "Iron Man": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/9/9d/Iron_Man_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Captain America": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/9/9d/Captain_America_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Thor": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/2/2b/Thor_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Hulk": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/2/29/Hulk_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Black Widow": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/3/3f/Black_Widow_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Hawkeye": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/5/5b/Hawkeye_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Spider-Man": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/4/41/Spider-Man_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Doctor Strange": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/b/b2/Doctor_Strange_MoM_Profile.jpeg/revision/latest/scale-to-width-down/400",
    "Black Panther": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/9/9d/T%27Challa_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Captain Marvel": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/3/3d/Captain_Marvel_Profile.png/revision/latest/scale-to-width-down/400",
    "Scarlet Witch": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/6/60/Scarlet_Witch_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Vision": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/6/6e/Vision_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Ant-Man": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/4/46/Ant-Man_Infobox.png/revision/latest/scale-to-width-down/400",
    "The Wasp": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/2/22/Wasp_Quantumania.jpg/revision/latest/scale-to-width-down/400",
    "Falcon": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/3/3d/Falcon_Infobox.png/revision/latest/scale-to-width-down/400",
    "Winter Soldier": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/2/21/Winter_Soldier_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "War Machine": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/7/77/WarMachine-EndgameProfile.jpg/revision/latest/scale-to-width-down/400",
    "Star-Lord": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/6/6c/Star-Lord_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Gamora": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/7/70/Gamora_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Drax": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/c/cd/Drax_Vol._3.jpg/revision/latest/scale-to-width-down/400",
    "Rocket": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/3/30/Rocket_Vol._3.jpg/revision/latest/scale-to-width-down/400",
    "Groot": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/5/57/Groot_Infobox.png/revision/latest/scale-to-width-down/400",
    "Mantis": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/2/27/Mantis_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Nebula": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/3/37/Nebula_Vol._3.jpg/revision/latest/scale-to-width-down/400",
    "Thanos": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/2/27/Thanos_Infobox.png/revision/latest/scale-to-width-down/400",
    "Loki": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/b/b5/Loki_Infobox.png/revision/latest/scale-to-width-down/400",
    "Ultron": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/6/6a/Ultron_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Hela": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/a/ae/Hela_Infobox.png/revision/latest/scale-to-width-down/400",
    "Wolverine": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/7/7c/Wolverine_Infobox.png/revision/latest/scale-to-width-down/400",
    "Deadpool": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/a/ad/Deadpool_Infobox.png/revision/latest/scale-to-width-down/400",
    "Professor X": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/0/06/Professor_X_Infobox.png/revision/latest/scale-to-width-down/400",
    "Magneto": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/4/41/Magneto_Infobox.png/revision/latest/scale-to-width-down/400",
    "Cyclops": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/3/3d/Cyclops_Infobox.png/revision/latest/scale-to-width-down/400",
    "Gambit": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/a/ab/Gambit_Infobox.png/revision/latest/scale-to-width-down/400",
    "Mystique": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/f/f8/Mystique_Infobox.jpeg/revision/latest/scale-to-width-down/400",
    "Juggernaut": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/0/07/Juggernaut.png/revision/latest/scale-to-width-down/400",
    "Nightcrawler": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/5/53/Nightcrawler_Infobox.jpeg/revision/latest/scale-to-width-down/400",
    "Silver Surfer": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/6/65/Shalla-Bal_%28Silver_Surfer%29_Infobox.png/revision/latest/scale-to-width-down/400",
    "Galactus": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/a/a7/Galactus.png/revision/latest/scale-to-width-down/400",
    "Doctor Doom": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/0/07/Doctor_Doom_Infobox.png/revision/latest/scale-to-width-down/400",
    "Mister Fantastic": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/9/9f/Mister_Fantastic_Infobox.png/revision/latest/scale-to-width-down/400",
    "Invisible Woman": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/6/69/Invisible_Woman_Infobox.png/revision/latest/scale-to-width-down/400",
    "Human Torch": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/b/b8/Human_Torch_Infobox.png/revision/latest/scale-to-width-down/400",
    "The Thing": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/2/2a/Thing_Infobox.png/revision/latest/scale-to-width-down/400",
    "Ghost Rider": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/8/80/Ghost_Rider_RR.jpg/revision/latest/scale-to-width-down/400",
    "Daredevil": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/d/d7/Daredevil_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "The Punisher": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/1/1c/Punisher_Infobox.png/revision/latest/scale-to-width-down/400",
    "Moon Knight": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/e/ea/Moon_Knight_Poster_Textless.png/revision/latest/scale-to-width-down/400",
    "Ms. Marvel": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/2/22/Ms._Marvel_Infobox.png/revision/latest/scale-to-width-down/400",
    "She-Hulk": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/5/5a/She-Hulk_-_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Shang-Chi": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/4/40/Shang-Chi_Profile.jpg/revision/latest/scale-to-width-down/400",
    "Carnage": "https://static.wikia.nocookie.net/marveldatabase/images/9/98/Carnage_Vol_4_1_Mastrazzo_Variant_Textless.jpg/revision/latest/scale-to-width-down/400",
    "Green Goblin": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/3/39/Green_Goblin_Infobox.png/revision/latest/scale-to-width-down/400",
    "Doctor Octopus": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/1/15/Doctor_Octopus_Infobox.png/revision/latest/scale-to-width-down/400",
    "Kang the Conqueror": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/e/e4/Kang_the_Conqueror_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Red Skull": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/6/6d/Red_Skull_Infobox.png/revision/latest/scale-to-width-down/400",
    "Namor": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/8/89/Namor_Profile.png/revision/latest/scale-to-width-down/400",
    "Adam Warlock": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/0/08/Adam_Warlock_Infobox.png/revision/latest/scale-to-width-down/400",
    "Nick Fury": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/a/a3/Nick_Fury_Infobox.png/revision/latest/scale-to-width-down/400",
    "Kingpin": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/9/9c/Kingpin_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Black Bolt": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/1/18/Black_Bolt.jpg/revision/latest/scale-to-width-down/400",
    "Okoye": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/2/25/Black_Panther_Wakanda_Forever_poster_024_Textless.jpg/revision/latest/scale-to-width-down/400",
    "Valkyrie": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/d/d8/Valkyrie_in_LoveAndThunder_Poster.png/revision/latest/scale-to-width-down/400",
    "Squirrel Girl": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/0/01/Squirrel_Girl.png/revision/latest/scale-to-width-down/400",
    "Howard the Duck": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/d/d0/Howard_duck.png/revision/latest/scale-to-width-down/400",
    "Storm": "https://static.wikia.nocookie.net/marveldatabase/images/9/9a/Storm_Vol_5_7_Textless.jpg/revision/latest/scale-to-width-down/400",
    "Phoenix": "https://static.wikia.nocookie.net/marveldatabase/images/6/64/Phoenix_Vol_1_11_Textless.jpg/revision/latest/scale-to-width-down/400",
    "Rogue": "https://static.wikia.nocookie.net/marveldatabase/images/b/bb/Uncanny_X-Men_Vol_6_34_Rogue_Virgin_Variant.jpg/revision/latest/scale-to-width-down/400",
    "Blade": "https://static.wikia.nocookie.net/marveldatabase/images/2/29/Blade_Vol_6_1_Textless.jpg/revision/latest/scale-to-width-down/400",
    "Venom": "https://static.wikia.nocookie.net/marveldatabase/images/b/b3/All-New_Venom_Vol_1_1_Lee_Virgin_Variant.jpg/revision/latest/scale-to-width-down/400",
    "Bullseye": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/1/1c/Bullseye_Infobox.png/revision/latest/scale-to-width-down/400",
    "Elektra": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/e/e3/Elektra_Infobox.png/revision/latest/scale-to-width-down/400",
    "Iron Fist": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/e/e7/Iron_Fist_%28S2%29.jpg/revision/latest/scale-to-width-down/400",
    "Luke Cage": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/1/10/Luke_Cage.PNG/revision/latest/scale-to-width-down/400",
    "Jessica Jones": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/8/8a/Jessica_Jones_Infobox.png/revision/latest/scale-to-width-down/400",
    "Misty Knight": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/e/e0/Misty_Knight.PNG/revision/latest/scale-to-width-down/400",
    "Cloak": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/e/ed/Cloak_Infobox.png/revision/latest/scale-to-width-down/400",
    "Dagger": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/a/a8/Dagger_Infobox.png/revision/latest/scale-to-width-down/400",
    "Morbius": "https://static.wikia.nocookie.net/marveldatabase/images/6/6c/Morbius_Vol_1_1_Textless.jpg/revision/latest/scale-to-width-down/400",
    "Kraven the Hunter": "https://static.wikia.nocookie.net/marveldatabase/images/8/83/Amazing_Spider-Man_Vol_5_19_ComicXposure_Exclusive_Virgin_Variant.jpg/revision/latest/scale-to-width-down/400",
    "Mysterio": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/5/51/Mysterio_Infobox.png/revision/latest/scale-to-width-down/400",
    "Vulture": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/2/23/Vulture.jpg/revision/latest/scale-to-width-down/400",
    "Rhino": "https://static.wikia.nocookie.net/marveldatabase/images/1/18/Aleksei_Sytsevich_%28Earth-616%29_from_Miles_Morales_Spider-Man_Vol_1_1_001.jpg/revision/latest/scale-to-width-down/400",
    "Scorpion": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/a/a4/Scorpion_Infobox.png/revision/latest/scale-to-width-down/400",
    "Electro": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/9/94/Electro_Infobox.png/revision/latest/scale-to-width-down/400",
    "Taskmaster": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/4/49/Taskmaster_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Crossbones": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/8/88/Crossbones_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Baron Zemo": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/d/d5/TF%26TWS_Textless_Character_Posters_02.jpg/revision/latest/scale-to-width-down/400",
    "Arnim Zola": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/6/67/Arnim_Zola.png/revision/latest/scale-to-width-down/400",
    "MODOK": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/c/c6/MODOK_%28Darren_Cross%29_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Ego": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/4/4c/Ego_Infobox.png/revision/latest/scale-to-width-down/400",
    "Yondu": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/9/9b/Yondu_Infobox.png/revision/latest/scale-to-width-down/400",
    "Cosmo": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/8/80/Cosmo_Vol3_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Beta Ray Bill": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/3/3b/Beta_Ray_Bill_Visage_pic.jpg/revision/latest?cb=20180421110618",
    "Gorr": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/7/71/Gorr_Infobox.png/revision/latest/scale-to-width-down/400",
    "Black Knight": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/2/2e/Black_Knight_Character_Poster.jpg/revision/latest/scale-to-width-down/400",
    "Hercules": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/7/76/Hercules.png/revision/latest/scale-to-width-down/400",
    "America Chavez": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/a/a8/America_Chavez.png/revision/latest/scale-to-width-down/400",
    "Kate Bishop": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/d/d9/Kate_Bishop_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Echo": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/d/d0/Echo_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Jubilee": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/c/c5/Jubilee.png/revision/latest/scale-to-width-down/400",
    "Colossus": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/b/bb/Colossus.png/revision/latest/scale-to-width-down/400",
    "Kitty Pryde": "https://static.wikia.nocookie.net/marveldatabase/images/1/16/Exceptional_X-Men_Vol_1_10_Pride_Variant_Textless.jpg/revision/latest/scale-to-width-down/400",
    "Iceman": "https://static.wikia.nocookie.net/marveldatabase/images/3/3a/X-Men_Vol_6_13_Trading_Card_Variant_Textless.jpg/revision/latest/scale-to-width-down/400",
    "Beast": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/8/86/Beast_Infobox.png/revision/latest/scale-to-width-down/400",
    "Psylocke": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/c/c2/Psylocke.png/revision/latest/scale-to-width-down/400",
    "Cable": "https://static.wikia.nocookie.net/marveldatabase/images/5/5d/Cable_Reloaded_Vol_1_1_Textless.jpg/revision/latest/scale-to-width-down/400",
    "Domino": "https://static.wikia.nocookie.net/marveldatabase/images/9/93/Domino_Vol_3_2_Textless.jpg/revision/latest/scale-to-width-down/400",
    "Emma Frost": "https://static.wikia.nocookie.net/marveldatabase/images/4/42/X-Men_United_Vol_1_1_Chew_Virgin_Variant.jpg/revision/latest/scale-to-width-down/400",
    "Apocalypse": "https://static.wikia.nocookie.net/marveldatabase/images/1/1b/Tomb_of_Apocalypse_Vol_1_1_Villalobos_Virgin_Variant.jpg/revision/latest/scale-to-width-down/400",
    "Sabretooth": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/5/59/Sabretooth.png/revision/latest/scale-to-width-down/400",
    "Sentry": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/7/70/Sentry_Infobox.png/revision/latest/scale-to-width-down/400",
    "Wonder Man": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/a/ac/Simon_Williams_Infobox.png/revision/latest/scale-to-width-down/400",
    "Hellcat": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/8/80/Trish_Walker.jpg/revision/latest/scale-to-width-down/400",
    "Werewolf by Night": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/b/bb/Werewolf_by_Night.png/revision/latest/scale-to-width-down/400",
    "Man-Thing": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/f/ff/Theodore_Sallis_29_from_Werewolf_by_Night_29_Promo_001.webp/revision/latest/scale-to-width-down/400",
    "Mephisto": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/8/80/Mephisto_Infobox.png/revision/latest/scale-to-width-down/400",
    "Dormammu": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/8/80/Dormammu.png/revision/latest/scale-to-width-down/400",
    "Knull": "https://static.wikia.nocookie.net/marveldatabase/images/3/3c/Knull_%28Earth-616%29_from_Queen_in_Black_Defenders_of_Light_and_Dark_Vol_1_3_001.jpg/revision/latest/scale-to-width-down/400",
    "Ghost": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/4/4f/Ghost_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Abomination": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/a/a4/Abomination_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "The Leader": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/c/c4/Samuel_Sterns_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Wong": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/0/00/Wong_in_She-Hulk.jpg/revision/latest/scale-to-width-down/400",
    "Agatha Harkness": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/a/a5/Agatha_Harkness_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Killmonger": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/9/9d/Black_Panther_Textless_Character_Poster_03.jpg/revision/latest/scale-to-width-down/400",
    "M'Baku": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/e/e4/M%27Baku_Infobox.png/revision/latest/scale-to-width-down/400",
    "Shuri": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/9/93/Black_Panther_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Nova": "https://static.wikia.nocookie.net/marveldatabase/images/9/99/Imperial_Vol_1_3_Just_Spectacular_Collection_Virgin_Variant.jpg/revision/latest/scale-to-width-down/400",
    "Ronan the Accuser": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/0/0f/Ronan_the_Accuser_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Grandmaster": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/9/92/Thor_Ragnarok_Textless_Character_Posters_06.jpg/revision/latest/scale-to-width-down/400",
    "The Collector": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/0/0d/Collector_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Batroc the Leaper": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/9/95/Baltroc_TF%26TWS.jpg/revision/latest/scale-to-width-down/400",
    "Doop": "https://static.wikia.nocookie.net/marveldatabase/images/f/f0/All-New_Doop_Vol_1_1_Granov_Variant_Textless.jpg/revision/latest/scale-to-width-down/400",
    "Throg": "https://static.wikia.nocookie.net/marveldatabase/images/b/be/Thor_Vol_6_18_Textless.jpg/revision/latest/scale-to-width-down/400",
    "Lockjaw": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/9/9d/Lockjaw.JPG/revision/latest/scale-to-width-down/400",
    "Jeff the Land Shark": "https://static.wikia.nocookie.net/marveldatabase/images/4/42/Jeff_the_Land_Shark_Vol_1_4_Arita_Variant_Textless.jpg/revision/latest/scale-to-width-down/400",
    "Tigra": "https://static.wikia.nocookie.net/marveldatabase/images/f/f3/Blood_Hunt_Vol_1_1_Artgerm_Virgin_Variant.jpg/revision/latest/scale-to-width-down/400",
    "Bob, Agent of Hydra": "https://static.wikia.nocookie.net/marveldatabase/images/c/c9/Bob_Dobalina_%28Earth-616%29_from_Deadpool_Vol_3_7_0002.jpg/revision/latest/scale-to-width-down/400",
    "Moon Girl": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/8/8b/Moon_Girl_Infobox.png/revision/latest/scale-to-width-down/400",
    "Forge": "https://static.wikia.nocookie.net/marveldatabase/images/8/80/X-Force_Vol_7_1_Forge_Virgin_Variant.jpg/revision/latest/scale-to-width-down/400",
    "Union Jack": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/4/4c/Falsworth.jpeg/revision/latest/scale-to-width-down/400",
    "Stick": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/d/dc/Stick_Profile.PNG/revision/latest/scale-to-width-down/400",
    "Ikaris": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/9/9b/Ikaris_Character_Poster.jpg/revision/latest/scale-to-width-down/400",
    "Thena": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/d/db/Thena_First_Look.jpg/revision/latest/scale-to-width-down/400",
    "Kingo": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/2/25/Kingo_Character_Poster.jpg/revision/latest/scale-to-width-down/400",
    "Leech": "https://static.wikia.nocookie.net/marveldatabase/images/3/30/Leech_%28Earth-616%29_from_X-Men_The_198_Vol_1_2_001.jpg/revision/latest/scale-to-width-down/400"
  },
  "league": {
    "Ahri": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ahri_0.jpg",
    "Yasuo": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yasuo_0.jpg",
    "Yone": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yone_0.jpg",
    "Lee Sin": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/LeeSin_0.jpg",
    "Master Yi": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/MasterYi_0.jpg",
    "Irelia": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Irelia_0.jpg",
    "Akali": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Akali_0.jpg",
    "Shen": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Shen_0.jpg",
    "Zed": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zed_0.jpg",
    "Kennen": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kennen_0.jpg",
    "Jinx": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jinx_0.jpg",
    "Vi": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Vi_0.jpg",
    "Caitlyn": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Caitlyn_0.jpg",
    "Jayce": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jayce_0.jpg",
    "Viktor": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Viktor_0.jpg",
    "Ekko": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ekko_0.jpg",
    "Ezreal": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ezreal_0.jpg",
    "Heimerdinger": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Heimerdinger_0.jpg",
    "Singed": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Singed_0.jpg",
    "Warwick": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Warwick_0.jpg",
    "Lux": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lux_0.jpg",
    "Garen": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Garen_0.jpg",
    "Jarvan IV": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/JarvanIV_0.jpg",
    "Xin Zhao": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/XinZhao_0.jpg",
    "Sylas": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sylas_0.jpg",
    "Darius": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Darius_0.jpg",
    "Draven": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Draven_0.jpg",
    "Katarina": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Katarina_0.jpg",
    "Swain": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Swain_0.jpg",
    "LeBlanc": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Leblanc_0.jpg",
    "Sion": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sion_0.jpg",
    "Ashe": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ashe_0.jpg",
    "Sejuani": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sejuani_0.jpg",
    "Lissandra": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lissandra_0.jpg",
    "Braum": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Braum_0.jpg",
    "Tryndamere": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Tryndamere_0.jpg",
    "Ornn": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ornn_0.jpg",
    "Volibear": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Volibear_0.jpg",
    "Anivia": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Anivia_0.jpg",
    "Leona": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Leona_0.jpg",
    "Diana": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Diana_0.jpg",
    "Pantheon": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Pantheon_0.jpg",
    "Aphelios": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Aphelios_0.jpg",
    "Aurelion Sol": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/AurelionSol_0.jpg",
    "Miss Fortune": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/MissFortune_0.jpg",
    "Gangplank": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Gangplank_0.jpg",
    "Graves": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Graves_0.jpg",
    "Twisted Fate": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/TwistedFate_0.jpg",
    "Pyke": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Pyke_0.jpg",
    "Thresh": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Thresh_0.jpg",
    "Viego": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Viego_0.jpg",
    "Senna": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Senna_0.jpg",
    "Lucian": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lucian_0.jpg",
    "Azir": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Azir_0.jpg",
    "Nasus": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nasus_0.jpg",
    "Renekton": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Renekton_0.jpg",
    "Xerath": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Xerath_0.jpg",
    "Rammus": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rammus_0.jpg",
    "Aatrox": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Aatrox_0.jpg",
    "Kayle": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kayle_0.jpg",
    "Morgana": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Morgana_0.jpg",
    "Mordekaiser": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Mordekaiser_0.jpg",
    "Kai'Sa": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kaisa_0.jpg",
    "Vel'Koz": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Velkoz_0.jpg",
    "Bard": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Bard_0.jpg",
    "Nocturne": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nocturne_0.jpg",
    "Fiddlesticks": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiddlesticks_0.jpg",
    "Sett": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sett_0.jpg",
    "Teemo": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Teemo_0.jpg",
    "Yuumi": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yuumi_0.jpg",
    "Annie": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Annie_0.jpg",
    "Blitzcrank": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Blitzcrank_0.jpg",
    "Malphite": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Malphite_0.jpg",
    "Gwen": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Gwen_0.jpg"
  },
  "pokemon": {
    "Pikachu": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png",
    "Charizard": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png",
    "Blastoise": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png",
    "Venusaur": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png",
    "Bulbasaur": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png",
    "Charmander": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png",
    "Squirtle": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png",
    "Mewtwo": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png",
    "Mew": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/151.png",
    "Gengar": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png",
    "Alakazam": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/65.png",
    "Machamp": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/68.png",
    "Gyarados": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/130.png",
    "Dragonite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/149.png",
    "Snorlax": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/143.png",
    "Lapras": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/131.png",
    "Arcanine": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/59.png",
    "Ninetales": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/38.png",
    "Kangaskhan": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/115.png",
    "Onix": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/95.png",
    "Steelix": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/208.png",
    "Hitmonlee": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/106.png",
    "Hitmonchan": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/107.png",
    "Golem": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/76.png",
    "Magikarp": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/129.png",
    "Psyduck": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/54.png",
    "Jigglypuff": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/39.png",
    "Slowbro": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/80.png",
    "Ditto": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/132.png",
    "Eevee": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png",
    "Umbreon": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/197.png",
    "Sylveon": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/700.png",
    "Lugia": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/249.png",
    "Ho-Oh": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/250.png",
    "Suicune": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/245.png",
    "Celebi": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/251.png",
    "Tyranitar": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/248.png",
    "Scizor": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/212.png",
    "Heracross": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/214.png",
    "Blaziken": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/257.png",
    "Sceptile": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/254.png",
    "Swampert": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/260.png",
    "Gardevoir": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/282.png",
    "Metagross": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/376.png",
    "Rayquaza": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/384.png",
    "Groudon": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/383.png",
    "Kyogre": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/382.png",
    "Jirachi": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/385.png",
    "Deoxys": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/386.png",
    "Infernape": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/392.png",
    "Garchomp": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/445.png",
    "Lucario": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/448.png",
    "Darkrai": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/491.png",
    "Dialga": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/483.png",
    "Palkia": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/484.png",
    "Giratina": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/487.png",
    "Arceus": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/493.png",
    "Zoroark": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/571.png",
    "Hydreigon": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/635.png",
    "Volcarona": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/637.png",
    "Conkeldurr": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/534.png",
    "Ferrothorn": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/598.png",
    "Greninja": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/658.png",
    "Aegislash": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/681.png",
    "Decidueye": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/724.png",
    "Incineroar": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/727.png",
    "Primarina": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/730.png",
    "Mimikyu": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/778.png",
    "Toxapex": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/748.png",
    "Necrozma": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/800.png",
    "Corviknight": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/823.png",
    "Dragapult": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/887.png",
    "Cinderace": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/815.png",
    "Zacian": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/888.png",
    "Zamazenta": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/889.png",
    "Eternatus": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/890.png",
    "Tinkaton": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/959.png",
    "Kingambit": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/983.png",
    "Ceruledge": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/937.png",
    "Annihilape": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/979.png",
    "Koraidon": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1007.png",
    "Miraidon": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1008.png"
  },
  "warriors": {
    "Firestar": "https://static.wikia.nocookie.net/warriors/images/6/67/Firestar.star.png/revision/latest/scale-to-width-down/400?cb=20251229000309",
    "Graystripe": "https://static.wikia.nocookie.net/warriors/images/1/10/Graystripe.star.png/revision/latest/scale-to-width-down/400?cb=20251229000329",
    "Sandstorm": "https://static.wikia.nocookie.net/warriors/images/4/46/Sandstorm.star.png/revision/latest/scale-to-width-down/400?cb=20260401020319",
    "Bluestar": "https://static.wikia.nocookie.net/warriors/images/2/22/Bluestar.star.png/revision/latest/scale-to-width-down/400?cb=20250402002459",
    "Tigerstar": "https://static.wikia.nocookie.net/warriors/images/8/8c/Tigerstar.TPB-3.png/revision/latest/scale-to-width-down/400?cb=20250930075032",
    "Scourge": "https://static.wikia.nocookie.net/warriors/images/f/f6/Scourge.leader.png/revision/latest/scale-to-width-down/400?cb=20240401220743",
    "Bramblestar": "https://static.wikia.nocookie.net/warriors/images/2/2c/Brambleclaw.star.png/revision/latest/scale-to-width-down/400?cb=20260401233731",
    "Squirrelflight": "https://static.wikia.nocookie.net/warriors/images/9/90/Squirrelstar.leader.png/revision/latest/scale-to-width-down/400?cb=20251229000213",
    "Leafpool": "https://static.wikia.nocookie.net/warriors/images/2/2b/Leafpool.star.png/revision/latest/scale-to-width-down/400?cb=20251229000513",
    "Jayfeather": "https://static.wikia.nocookie.net/warriors/images/7/7e/Jayfeather.FG-6.png/revision/latest/scale-to-width-down/400?cb=20250402002539",
    "Lionblaze": "https://static.wikia.nocookie.net/warriors/images/3/38/Lionblaze.warrior.png/revision/latest/scale-to-width-down/400?cb=20250402002832",
    "Dovewing": "https://static.wikia.nocookie.net/warriors/images/e/e1/Dovewing.warrior.png/revision/latest/scale-to-width-down/400?cb=20251105224612",
    "Ivypool": "https://static.wikia.nocookie.net/warriors/images/7/7d/Ivypool.deputy.png/revision/latest/scale-to-width-down/400?cb=20251229000509",
    "Hollyleaf": "https://static.wikia.nocookie.net/warriors/images/e/ea/Hollyleaf.star.png/revision/latest/scale-to-width-down/400?cb=20251229000326",
    "Crowfeather": "https://static.wikia.nocookie.net/warriors/images/0/0f/Crowfeather.deputy.png/revision/latest/scale-to-width-down/400?cb=20250402002001",
    "Onestar": "https://static.wikia.nocookie.net/warriors/images/6/67/Onestar.star.png/revision/latest/scale-to-width-down/400?cb=20260425155946",
    "Leopardstar": "https://static.wikia.nocookie.net/warriors/images/f/fb/Leopardstar.star.png/revision/latest/scale-to-width-down/400?cb=20251229000347",
    "Blackstar": "https://static.wikia.nocookie.net/warriors/images/1/18/Blackstar.star.png/revision/latest/scale-to-width-down/400?cb=20250402002455",
    "Tallstar": "https://static.wikia.nocookie.net/warriors/images/e/e5/Tallstar.star.png/revision/latest/scale-to-width-down/400?cb=20241223093009",
    "Yellowfang": "https://static.wikia.nocookie.net/warriors/images/b/b3/Yellowfang.star.png/revision/latest/scale-to-width-down/400?cb=20241222021822",
    "Spottedleaf": "https://static.wikia.nocookie.net/warriors/images/0/05/Spottedleaf.star.png/revision/latest/scale-to-width-down/400?cb=20251229000230",
    "Ravenpaw": "https://static.wikia.nocookie.net/warriors/images/b/b4/Ravenpaw.unknown.png/revision/latest/scale-to-width-down/400?cb=20251229000333",
    "Cinderpelt": "https://static.wikia.nocookie.net/warriors/images/7/7b/Cinderpelt.star.png/revision/latest/scale-to-width-down/400?cb=20250402000413",
    "Mothwing": "https://static.wikia.nocookie.net/warriors/images/a/ad/Mothwing.TNP-1.png/revision/latest/scale-to-width-down/400?cb=20260630190620",
    "Hawkfrost": "https://static.wikia.nocookie.net/warriors/images/0/02/Hawkfrost.TNP-1.png/revision/latest/scale-to-width-down/400?cb=20260719184917",
    "Mapleshade": "https://static.wikia.nocookie.net/warriors/images/0/0b/Mapleshade.FG-8.png/revision/latest/scale-to-width-down/400?cb=20251105225847",
    "Brokenstar": "https://static.wikia.nocookie.net/warriors/images/6/61/Brokenstar.FG-8.png/revision/latest/scale-to-width-down/400?cb=20250402001613",
    "Darkstripe": "https://static.wikia.nocookie.net/warriors/images/9/9a/Darkstripe.TPB-1.png/revision/latest/scale-to-width-down/400?cb=20250402003120",
    "Mistystar": "https://static.wikia.nocookie.net/warriors/images/f/f5/Mistystar.star.png/revision/latest/scale-to-width-down/400?cb=20251229000113",
    "Rowanstar": "https://static.wikia.nocookie.net/warriors/images/1/1d/Rowanclaw.star.png/revision/latest/scale-to-width-down/400?cb=20250402000216",
    "Ashfur": "https://static.wikia.nocookie.net/warriors/images/b/b4/Ashfur_%28TC%29.ghost.png/revision/latest/scale-to-width-down/400?cb=20250227004831",
    "Feathertail": "https://static.wikia.nocookie.net/warriors/images/d/d6/Feathertail.toeh.png/revision/latest/scale-to-width-down/400?cb=20251229000125",
    "Stormfur": "https://static.wikia.nocookie.net/warriors/images/9/9f/Stormfur.cg.png/revision/latest/scale-to-width-down/400?cb=20200928080830",
    "Cloudtail": "https://static.wikia.nocookie.net/warriors/images/f/f0/Cloudtail.elder.png/revision/latest/scale-to-width-down/400?cb=20250520012045",
    "Brightheart": "https://static.wikia.nocookie.net/warriors/images/7/76/Brightheart.elder.png/revision/latest/scale-to-width-down/400?cb=20251105230226",
    "Whitestorm": "https://static.wikia.nocookie.net/warriors/images/5/55/Whitestorm.star.png/revision/latest/scale-to-width-down/400?cb=20250402002442",
    "Lionheart": "https://static.wikia.nocookie.net/warriors/images/8/8e/Lionheart.star.png/revision/latest/scale-to-width-down/400?cb=20241228214843",
    "Mudclaw": "https://static.wikia.nocookie.net/warriors/images/a/a3/Mudclaw_%28WiC%29.star.png/revision/latest/scale-to-width-down/400?cb=20230402001225",
    "Sol": "https://static.wikia.nocookie.net/warriors/images/d/d6/Sol.FG-6.png/revision/latest/scale-to-width-down/400?cb=20250402002249",
    "Clear Sky": "https://static.wikia.nocookie.net/warriors/images/d/d1/Skystar.star.png/revision/latest/scale-to-width-down/400?cb=20250402002100",
    "Gray Wing": "https://static.wikia.nocookie.net/warriors/images/8/87/Gray_Wing.star.png/revision/latest/scale-to-width-down/400?cb=20250402002216",
    "Thunder": "https://static.wikia.nocookie.net/warriors/images/0/04/Thunderstar.star.png/revision/latest/scale-to-width-down/400?cb=20250402003325",
    "Wind Runner": "https://static.wikia.nocookie.net/warriors/images/2/20/Windstar.star.png/revision/latest/scale-to-width-down/400?cb=20250402002614",
    "River Ripple": "https://static.wikia.nocookie.net/warriors/images/4/4a/Riverstar.star.png/revision/latest/scale-to-width-down/400?cb=20251229000037",
    "Tall Shadow": "https://static.wikia.nocookie.net/warriors/images/f/fe/Shadowstar.star.png/revision/latest/scale-to-width-down/400?cb=20251109025350",
    "Shadowsight": "https://static.wikia.nocookie.net/warriors/images/7/73/Shadowsight.TBC-1.png/revision/latest/scale-to-width-down/400?cb=20250402001253",
    "Rootspring": "https://static.wikia.nocookie.net/warriors/images/1/14/Rootspring.warrior.png/revision/latest/scale-to-width-down/400?cb=20241223034422",
    "Alderheart": "https://static.wikia.nocookie.net/warriors/images/0/08/Alderheart.VOS-1.png/revision/latest/scale-to-width-down/400?cb=20251109025647",
    "Nightheart": "https://static.wikia.nocookie.net/warriors/images/e/eb/Nightheart_%28ASC%29.warrior.png/revision/latest/scale-to-width-down/400?cb=20251106225459",
    "Leafstar": "https://static.wikia.nocookie.net/warriors/images/2/24/Leafstar.leader.png/revision/latest/scale-to-width-down/400?cb=20251229000429",
    "Hawkwing": "https://static.wikia.nocookie.net/warriors/images/2/28/Hawkwing.deputy.png/revision/latest/scale-to-width-down/400?cb=20250402002435",
    "Ferncloud": "https://static.wikia.nocookie.net/warriors/images/7/76/Ferncloud.star.png/revision/latest/scale-to-width-down/400?cb=20241223040246",
    "Longtail": "https://static.wikia.nocookie.net/warriors/images/8/82/Longtail.star.png/revision/latest/scale-to-width-down/400?cb=20250402001221",
    "Rusty": "https://static.wikia.nocookie.net/warriors/images/6/67/Firestar.star.png/revision/latest/scale-to-width-down/400?cb=20251229000309",
    "Midnight": "https://static.wikia.nocookie.net/warriors/images/5/55/Midnight.FG-6.png/revision/latest/scale-to-width-down/400?cb=20251105230924",
    "Stoneteller": "https://static.wikia.nocookie.net/warriors/images/a/a1/Teller_of_the_Pointed_Stones_%28TNP%29.toeh.png/revision/latest/scale-to-width-down/400?cb=20240810045530",
    "Sharptooth": "https://static.wikia.nocookie.net/warriors/images/a/ac/Sharptooth_%28creature%29.jpg/revision/latest/scale-to-width-down/400?cb=20260916040917",
    "Fireheart": "https://static.wikia.nocookie.net/warriors/images/6/67/Firestar.star.png/revision/latest/scale-to-width-down/400?cb=20251229000309",
    "Tawnypelt": "https://static.wikia.nocookie.net/warriors/images/2/27/Tawnypelt.warrior.png/revision/latest/scale-to-width-down/400?cb=20240401201859",
    "Crookedstar": "https://static.wikia.nocookie.net/warriors/images/1/12/Crookedstar.star.png/revision/latest/scale-to-width-down/400?cb=20250402002428"
  },
  "anime": {
    "Goku": "https://s4.anilist.co/file/anilistcdn/character/large/246-wsRRr6z1kii8.png",
    "Naruto Uzumaki": "https://s4.anilist.co/file/anilistcdn/character/large/b17-phjcWCkRuIhu.png",
    "Monkey D. Luffy": "https://s4.anilist.co/file/anilistcdn/character/large/b40-MNypXsxSRb1R.png",
    "Ichigo Kurosaki": "https://s4.anilist.co/file/anilistcdn/character/large/b5-a7bkJgjhhigE.png",
    "Saitama": "https://s4.anilist.co/file/anilistcdn/character/large/b73935-ON5d0mAcrItd.jpg",
    "Izuku Midoriya": "https://s4.anilist.co/file/anilistcdn/character/large/b89028-8w1I9o1ISHMg.png",
    "Gon Freecss": "https://s4.anilist.co/file/anilistcdn/character/large/b30-lyFExKyDhefc.jpg",
    "Killua Zoldyck": "https://s4.anilist.co/file/anilistcdn/character/large/b27-Z5O02kQUydpT.jpg",
    "Eren Yeager": "https://s4.anilist.co/file/anilistcdn/character/large/b40882-dsj7IP943WFF.jpg",
    "Tanjiro Kamado": "https://s4.anilist.co/file/anilistcdn/character/large/b126071-BTNEc1nRIv68.png",
    "Yuji Itadori": "https://s4.anilist.co/file/anilistcdn/character/large/b127212-FVm2tD0erQ5B.png",
    "Light Yagami": "https://s4.anilist.co/file/anilistcdn/character/large/b80-26EhwSsSqQ50.png",
    "Edward Elric": "https://s4.anilist.co/file/anilistcdn/character/large/b11-TA5Nuk7EDUZG.jpg",
    "Spike Spiegel": "https://s4.anilist.co/file/anilistcdn/character/large/b1-ChxaldmieFlQ.png",
    "Lelouch Lamperouge": "https://s4.anilist.co/file/anilistcdn/character/large/b417-gVLmIJu9phcK.png",
    "Vash the Stampede": "https://s4.anilist.co/file/anilistcdn/character/large/b162-kfdfqsX7Xjf0.png",
    "Asta": "https://s4.anilist.co/file/anilistcdn/character/large/b123285-tKijiuQErDS0.png",
    "Denji": "https://s4.anilist.co/file/anilistcdn/character/large/b130102-FO1VHNnEnLlB.png",
    "Usagi Tsukino": "https://s4.anilist.co/file/anilistcdn/character/large/b2030-GQvVYPEYkXCy.jpg",
    "Inuyasha": "https://s4.anilist.co/file/anilistcdn/character/large/b1353-xsZhvfi7IFzT.png",
    "Yusuke Urameshi": "https://s4.anilist.co/file/anilistcdn/character/large/b729-V6GlADOEZv3x.png",
    "Kenshiro": "https://s4.anilist.co/file/anilistcdn/character/large/b2511-I5ff3jioC5Ze.jpg",
    "Jotaro Kujo": "https://s4.anilist.co/file/anilistcdn/character/large/b4003-gWDSEGbeOAll.png",
    "Giorno Giovanna": "https://s4.anilist.co/file/anilistcdn/character/large/b10529-AloL8jjZwjsg.png",
    "Kirito": "https://s4.anilist.co/file/anilistcdn/character/large/b36765-BnLbXg0Tzzh9.png",
    "Rimuru Tempest": "https://s4.anilist.co/file/anilistcdn/character/large/b123962-eL9yGV0NLMF7.png",
    "Ainz Ooal Gown": "https://s4.anilist.co/file/anilistcdn/character/large/b89103-ZsnA0r77GHsR.png",
    "Shinji Ikari": "https://s4.anilist.co/file/anilistcdn/character/large/b89-ZtZhXkh1rITn.png",
    "Senku Ishigami": "https://s4.anilist.co/file/anilistcdn/character/large/b124142-XUO1g7wRqkaT.png",
    "Shigeo Kageyama": "https://s4.anilist.co/file/anilistcdn/character/large/b89616-dXmdOc7L6SDi.png",
    "Thorfinn": "https://s4.anilist.co/file/anilistcdn/character/large/b10138-zOPrka0ddZOR.png",
    "Guts": "https://s4.anilist.co/file/anilistcdn/character/large/b422-XTaiTuvRohsV.png",
    "Natsu Dragneel": "https://s4.anilist.co/file/anilistcdn/character/large/b5187-y1OEdRu9sPN2.png",
    "Yugi Muto": "https://s4.anilist.co/file/anilistcdn/character/large/b1374-dZVmlraKNPp3.jpg",
    "Kenshin Himura": "https://s4.anilist.co/file/anilistcdn/character/large/b147-miunGYp6fkzb.png",
    "Motoko Kusanagi": "https://s4.anilist.co/file/anilistcdn/character/large/b1795-vKakY5aXVyCl.jpg",
    "Simon": "https://s4.anilist.co/file/anilistcdn/character/large/b2257-jnalsdnIX1vN.jpg",
    "Ryuko Matoi": "https://s4.anilist.co/file/anilistcdn/character/large/b83797-ix0Cl5OMfV22.png",
    "Loid Forger": "https://s4.anilist.co/file/anilistcdn/character/large/b138101-7NCB0Md8zA6G.png",
    "Frieren": "https://s4.anilist.co/file/anilistcdn/character/large/b176754-PCnpqIOkjhFk.png",
    "Kazuma Sato": "https://s4.anilist.co/file/anilistcdn/character/large/b89364-7Th8Tv1XKJtt.png",
    "Subaru Natsuki": "https://s4.anilist.co/file/anilistcdn/character/large/b88573-F8yMTK9GhnTA.png",
    "Ken Kaneki": "https://s4.anilist.co/file/anilistcdn/character/large/b87275-mb13EWZBdbh3.png",
    "Gintoki Sakata": "https://s4.anilist.co/file/anilistcdn/character/large/b672-cP5VPriN67xJ.png",
    "Rintaro Okabe": "https://s4.anilist.co/file/anilistcdn/character/large/b35252-DY9TW6pusqeh.png",
    "Conan Edogawa": "https://s4.anilist.co/file/anilistcdn/character/large/b1742-NiV278NBFOvZ.png",
    "Violet Evergarden": "https://s4.anilist.co/file/anilistcdn/character/large/b90169-4wr1Zehnsac8.png",
    "Alphonse Elric": "https://s4.anilist.co/file/anilistcdn/character/large/b12-tCKu8yK5kFL5.jpg",
    "Kafka Hibino": "https://s4.anilist.co/file/anilistcdn/character/large/b180692-rPGXuxhcKw5N.png",
    "Mash Burnedead": "https://s4.anilist.co/file/anilistcdn/character/large/b158734-k8FAVIyXKdW1.jpg",
    "Tsunayoshi Sawada": "https://s4.anilist.co/file/anilistcdn/character/large/b670-ZK5VTiy59C1M.png",
    "Yato": "https://s4.anilist.co/file/anilistcdn/character/large/b84677-PFmohzIXD1ud.png",
    "Mugen": "https://s4.anilist.co/file/anilistcdn/character/large/b390-30DZg8NvIrVk.png",
    "Rudeus Greyrat": "https://s4.anilist.co/file/anilistcdn/character/large/b88348-bIe5XnXdRpmX.png",
    "Joseph Joestar": "https://s4.anilist.co/file/anilistcdn/character/large/b6356-RImEfUfHpC58.png",
    "Akira Fudo": "https://s4.anilist.co/file/anilistcdn/character/large/b2456-rTjIXMLPHTu2.jpg",
    "Momo Ayase": "https://s4.anilist.co/file/anilistcdn/character/large/b222594-24Jn7qlI5spH.png",
    "Sung Jinwoo": "https://s4.anilist.co/file/anilistcdn/character/large/b129928-BCEjVaP0AQSw.png",
    "Shotaro Kaneda": "https://s4.anilist.co/file/anilistcdn/character/large/b2588-OfACKXYm2lkV.png",
    "Vegeta": "https://s4.anilist.co/file/anilistcdn/character/large/b913-NIFkKazWM8VO.png",
    "Sasuke Uchiha": "https://s4.anilist.co/file/anilistcdn/character/large/b13-SISLEw1oAD7a.png",
    "Roronoa Zoro": "https://s4.anilist.co/file/anilistcdn/character/large/b62-S7oAeA9WInjV.png",
    "All Might": "https://s4.anilist.co/file/anilistcdn/character/large/b89224-K6KEuQAuYKzq.jpg",
    "Mikasa Ackerman": "https://s4.anilist.co/file/anilistcdn/character/large/b40881-F3gr1PkreDvj.png",
    "Nezuko Kamado": "https://s4.anilist.co/file/anilistcdn/character/large/b127518-NRlq1CQ1v1ro.png",
    "Hisoka": "https://s4.anilist.co/file/anilistcdn/character/large/b31-FZckOuu7L1un.png",
    "L": "https://s4.anilist.co/file/anilistcdn/character/large/b71-1W4panC53vfs.png",
    "Makima": "https://s4.anilist.co/file/anilistcdn/character/large/b137080-UHcynYNjb5ZU.png",
    "Satoru Gojo": "https://s4.anilist.co/file/anilistcdn/character/large/b127691-9zqh1xpIubn7.png",
    "Levi Ackerman": "https://s4.anilist.co/file/anilistcdn/character/large/b45627-CR68RyZmddGG.png",
    "Kakashi Hatake": "https://s4.anilist.co/file/anilistcdn/character/large/b85-mkVBh2yjxjmx.png",
    "Itachi Uchiha": "https://s4.anilist.co/file/anilistcdn/character/large/b14-9Kb1E5oel1ke.png",
    "Ryomen Sukuna": "https://s4.anilist.co/file/anilistcdn/character/large/b133701-rCQuDpHr3UZL.png",
    "Frieza": "https://s4.anilist.co/file/anilistcdn/character/large/b3694-bDfOdSSdFfPv.png",
    "Sosuke Aizen": "https://s4.anilist.co/file/anilistcdn/character/large/b1086-qR9218BjZTC0.png",
    "Dio Brando": "https://s4.anilist.co/file/anilistcdn/character/large/b4004-w0OtWuvjhftG.png",
    "Kyojuro Rengoku": "https://s4.anilist.co/file/anilistcdn/character/large/b129133-VlTPowwt68rJ.png",
    "Kurapika": "https://s4.anilist.co/file/anilistcdn/character/large/b28-ivA7UGnfE40a.png",
    "Shanks": "https://s4.anilist.co/file/anilistcdn/character/large/b727-wUJx7M1z5xON.png",
    "Power": "https://s4.anilist.co/file/anilistcdn/character/large/b137079-6yLEUYR3bmpr.png",
    "Megumin": "https://s4.anilist.co/file/anilistcdn/character/large/b89361-tq8PQQ4MmF0M.png",
    "Madara Uchiha": "https://s4.anilist.co/file/anilistcdn/character/large/b53901-HnRKSoHMG5Vg.png",
    "Zenitsu Agatsuma": "https://s4.anilist.co/file/anilistcdn/character/large/b129131-FZrQ7lSlxmEr.png",
    "Portgas D. Ace": "https://s4.anilist.co/file/anilistcdn/character/large/b2072-Lc6jEdsueJUK.jpg",
    "Erwin Smith": "https://s4.anilist.co/file/anilistcdn/character/large/b46496-Mu86MENd5wNB.png"
  },
  "dc": {
    "Superman": "https://static.wikia.nocookie.net/marvel_dc/images/0/08/Summer_of_Superman_Special_Vol_1_1_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20250416152204",
    "Batman": "https://static.wikia.nocookie.net/marvel_dc/images/0/08/Batman_Vol_3_131_Textless_Fabok_Variant.jpg/revision/latest/scale-to-width-down/400?cb=20230106222502",
    "Wonder Woman": "https://static.wikia.nocookie.net/marvel_dc/images/c/c6/Wonder_Woman_Vol_6_1_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20230919192422",
    "The Flash": "https://static.wikia.nocookie.net/marvel_dc/images/7/74/Flash_0006.jpg/revision/latest/scale-to-width-down/400?cb=20120215162619",
    "Green Lantern": "https://static.wikia.nocookie.net/marvel_dc/images/2/2d/The_Green_Lantern_Vol_1_1_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20181108024532",
    "Aquaman": "https://static.wikia.nocookie.net/marvel_dc/images/8/88/Aquaman_Vol_9_1_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20250109012456",
    "Cyborg": "https://static.wikia.nocookie.net/marvel_dc/images/6/69/Justice_League_Vol_4_5_Textless_Variant.jpg/revision/latest/scale-to-width-down/400?cb=20190512225357",
    "Martian Manhunter": "https://static.wikia.nocookie.net/marvel_dc/images/4/49/Martian_Manhunter_Vol_5_1_Textless_Variant.jpg/revision/latest/scale-to-width-down/400?cb=20181205234853",
    "Green Arrow": "https://static.wikia.nocookie.net/marvel_dc/images/2/29/Green_Arrow_Vol_6_1_Textless_Variant.jpg/revision/latest/scale-to-width-down/400?cb=20160617025432",
    "Black Canary": "https://static.wikia.nocookie.net/marvel_dc/images/6/6f/Black_Canary_0003.jpg/revision/latest/scale-to-width-down/400?cb=20120209070457",
    "Shazam": "https://static.wikia.nocookie.net/marvel_dc/images/6/61/Shazam%21_Vol_3_1_Textless_Variant.jpg/revision/latest/scale-to-width-down/400?cb=20181205234924",
    "Supergirl": "https://static.wikia.nocookie.net/marvel_dc/images/a/a6/Supergirl_Vol_8_1_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20250515012052",
    "Superboy": "https://static.wikia.nocookie.net/marvel_dc/images/c/c8/Young_Justice_Vol_3_15_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20200616170256",
    "Nightwing": "https://static.wikia.nocookie.net/marvel_dc/images/4/41/Nightwing_Vol_4_105_Textless_Mora_Variant.jpg/revision/latest/scale-to-width-down/400?cb=20251207094133",
    "Robin": "https://static.wikia.nocookie.net/marvel_dc/images/1/1c/Batman_and_Robin_Vol_3_27_Textless_Chew_Variant.jpg/revision/latest/scale-to-width-down/400?cb=20251113140155",
    "Batgirl": "https://static.wikia.nocookie.net/marvel_dc/images/a/a4/Batman_Vol_3_104_Textless_Barbara_Gordon_Variant.jpg/revision/latest/scale-to-width-down/400?cb=20210420215552",
    "Red Hood": "https://static.wikia.nocookie.net/marvel_dc/images/2/2b/Red_Hood_The_Hill_Vol_1_5_Textless_Variant.jpg/revision/latest/scale-to-width-down/400?cb=20240615144945",
    "Catwoman": "https://static.wikia.nocookie.net/marvel_dc/images/7/7a/Catwoman_Vol_5_8_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20190225002106",
    "Raven": "https://static.wikia.nocookie.net/marvel_dc/images/3/3f/Raven_002.jpg/revision/latest/scale-to-width-down/400?cb=20051027194450",
    "Starfire": "https://static.wikia.nocookie.net/marvel_dc/images/7/7a/Tales_of_the_Titans_Vol_1_1_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20230817142619",
    "Beast Boy": "https://static.wikia.nocookie.net/marvel_dc/images/8/85/Tales_of_the_Titans_Vol_1_4_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20231024091129",
    "Blue Beetle": "https://static.wikia.nocookie.net/marvel_dc/images/4/45/Blue_Beetle_Vol_9_3_Textless_Variant.jpg/revision/latest/scale-to-width-down/400?cb=20161124081521",
    "Booster Gold": "https://static.wikia.nocookie.net/marvel_dc/images/b/b4/Booster_Gold_Prime_Earth_0009.png/revision/latest/scale-to-width-down/400?cb=20241002183549",
    "Hawkman": "https://static.wikia.nocookie.net/marvel_dc/images/2/25/Hawkman_Vol_5_1_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20180613183242",
    "Zatanna": "https://static.wikia.nocookie.net/marvel_dc/images/d/da/Zatanna_Prime_Earth_0019.jpeg/revision/latest/scale-to-width-down/400?cb=20250219204554",
    "John Constantine": "https://static.wikia.nocookie.net/marvel_dc/images/e/e8/Constantine_Vol_1_1_Textless_Variant.jpg/revision/latest/scale-to-width-down/400?cb=20130321202356",
    "Doctor Fate": "https://static.wikia.nocookie.net/marvel_dc/images/c/ca/Kent_Nelson_PE_01.jpg/revision/latest/scale-to-width-down/400?cb=20160607041258",
    "Swamp Thing": "https://static.wikia.nocookie.net/marvel_dc/images/0/0b/Swamp_Thing_Vol_5_25_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20131106222450",
    "Plastic Man": "https://static.wikia.nocookie.net/marvel_dc/images/6/64/Plastic_Man_Vol_5_3_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20180809183654",
    "The Atom": "https://static.wikia.nocookie.net/marvel_dc/images/d/da/Justice_League_of_America_Vol_5_16_Textless_Variant.jpg/revision/latest/scale-to-width-down/400?cb=20200312183637",
    "Firestorm": "https://static.wikia.nocookie.net/marvel_dc/images/1/1f/The_Fury_of_Firestorm_Vol_2_1_Textless.png/revision/latest/scale-to-width-down/400?cb=20260409035314",
    "John Stewart": "https://static.wikia.nocookie.net/marvel_dc/images/3/37/Green_Lantern_The_Lost_Army_Vol_1_3_Variant_B.jpg/revision/latest/scale-to-width-down/400?cb=20150820004846",
    "Guy Gardner": "https://static.wikia.nocookie.net/marvel_dc/images/5/5a/Guy_Gardner_Prime_Earth_001.jpg/revision/latest/scale-to-width-down/400?cb=20130511011521",
    "Black Adam": "https://static.wikia.nocookie.net/marvel_dc/images/5/50/Black_Adam_Vol_1_1_Textless_Jan%C3%ADn_Variant.jpg/revision/latest/scale-to-width-down/400?cb=20220625090649",
    "Batwoman": "https://static.wikia.nocookie.net/marvel_dc/images/4/4f/Batwoman_Vol_2_9_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20130711013448",
    "Static": "https://static.wikia.nocookie.net/marvel_dc/images/4/47/Static_Shock_Vol_1_1_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20160218185114",
    "Mister Miracle": "https://static.wikia.nocookie.net/marvel_dc/images/a/ab/Mister_Miracle_Scott_Free_0003.jpg/revision/latest/scale-to-width-down/400?cb=20091029025125",
    "Big Barda": "https://static.wikia.nocookie.net/marvel_dc/images/5/5f/Big_Barda_Prime_Earth_0002.jpg/revision/latest/scale-to-width-down/400?cb=20151224002616",
    "The Question": "https://static.wikia.nocookie.net/marvel_dc/images/b/bf/Victor_Sage_The_Question_%28Prime_Earth%29.jpg/revision/latest/scale-to-width-down/400?cb=20181129223948",
    "The Spectre": "https://static.wikia.nocookie.net/marvel_dc/images/7/70/Spectre_%28New_52%29_004.png/revision/latest/scale-to-width-down/400?cb=20130615204552",
    "Steel": "https://static.wikia.nocookie.net/marvel_dc/images/7/72/Action_Comics_Vol_1_1083_Textless_Benjamin_Variant.jpg/revision/latest/scale-to-width-down/400?cb=20250215232139",
    "Joker": "https://static.wikia.nocookie.net/marvel_dc/images/4/41/Batman_Vol_2_23.1_The_Joker_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20130904201016",
    "Harley Quinn": "https://static.wikia.nocookie.net/marvel_dc/images/8/8a/Harley_Quinn_Vol_3_1_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20160518093310",
    "Lex Luthor": "https://static.wikia.nocookie.net/marvel_dc/images/4/4e/Doomsday_Clock_Vol_1_2_Variant_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20180104222951",
    "Darkseid": "https://static.wikia.nocookie.net/marvel_dc/images/0/0e/Darkseid_Prime_Earth_012.png/revision/latest/scale-to-width-down/400?cb=20240419013644",
    "Brainiac": "https://static.wikia.nocookie.net/marvel_dc/images/c/c0/Justice_League_Vol_4_18_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20190225002124",
    "General Zod": "https://static.wikia.nocookie.net/marvel_dc/images/6/6f/Superman_Vol_6_42_Textless_Sampere_Variant.jpg/revision/latest/scale-to-width-down/400?cb=20260926045558",
    "Doomsday": "https://static.wikia.nocookie.net/marvel_dc/images/a/a8/Batman_Superman_Vol_1_3.1_Doomsday_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20130925200353",
    "Bane": "https://static.wikia.nocookie.net/marvel_dc/images/b/b0/Batman_Vol_3_18_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20170301040609",
    "Ra's al Ghul": "https://static.wikia.nocookie.net/marvel_dc/images/3/32/Batman_One_Bad_Day_Ra%27s_al_Ghul_Textless.png/revision/latest/scale-to-width-down/400?cb=20230323212039",
    "Talia al Ghul": "https://static.wikia.nocookie.net/marvel_dc/images/8/84/Batman_Incorporated_Vol_2_2_Textless_Variant.jpg/revision/latest/scale-to-width-down/400?cb=20181027144319",
    "Deathstroke": "https://static.wikia.nocookie.net/marvel_dc/images/f/fe/Deathstroke_Vol_3_3_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20141224184026",
    "Poison Ivy": "https://static.wikia.nocookie.net/marvel_dc/images/c/c7/Poison_Ivy_Vol_1_1_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20220608062955",
    "Two-Face": "https://static.wikia.nocookie.net/marvel_dc/images/c/cf/Two-Face_Vol_1_1_Textless_Samnee_Variant.jpg/revision/latest/scale-to-width-down/400?cb=20241205040145",
    "The Riddler": "https://static.wikia.nocookie.net/marvel_dc/images/3/3c/Batman_Vol_4_3_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20251105164929",
    "Penguin": "https://static.wikia.nocookie.net/marvel_dc/images/1/1c/Batman_Vol_2_23.3_The_Penguin_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20130918202628",
    "Scarecrow": "https://static.wikia.nocookie.net/marvel_dc/images/f/fa/Scarecrow_Prime_Earth_0002.jpg/revision/latest/scale-to-width-down/400?cb=20210307204046",
    "Mr. Freeze": "https://static.wikia.nocookie.net/marvel_dc/images/8/8f/Mister_Freeze_Prime_Earth_0001.jpg/revision/latest/scale-to-width-down/400?cb=20130822212807",
    "Killer Croc": "https://static.wikia.nocookie.net/marvel_dc/images/c/c8/Batman_and_Robin_Vol_2_23.4_Killer_Croc_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20130925195937",
    "Sinestro": "https://static.wikia.nocookie.net/marvel_dc/images/d/db/Green_Lantern_Vol_5_23.4_Sinestro_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20130925201722",
    "Black Manta": "https://static.wikia.nocookie.net/marvel_dc/images/7/72/Aquaman_Vol_7_12_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20120829165243",
    "Cheetah": "https://static.wikia.nocookie.net/marvel_dc/images/a/a4/Barbara_Minerva_Prime_Earth_010.png/revision/latest/scale-to-width-down/400?cb=20240618194131",
    "Reverse-Flash": "https://static.wikia.nocookie.net/marvel_dc/images/9/9a/Batman_Vol_3_22_Textless_2.jpg/revision/latest/scale-to-width-down/400?cb=20170504015809",
    "Gorilla Grodd": "https://static.wikia.nocookie.net/marvel_dc/images/8/8b/Gorilla_Grodd_0002.jpg/revision/latest/scale-to-width-down/400?cb=20191221130814",
    "Captain Cold": "https://static.wikia.nocookie.net/marvel_dc/images/a/a6/The_Flash_Vol_5_37_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20180111155826",
    "Deadshot": "https://static.wikia.nocookie.net/marvel_dc/images/3/33/Justice_League_of_America_Vol_3_7.1_Deadshot_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20130904215536",
    "Amanda Waller": "https://static.wikia.nocookie.net/marvel_dc/images/5/5f/Suicide_Squad_Vol_5_11_Textless_Variant.jpg/revision/latest/scale-to-width-down/400?cb=20170210191730",
    "Lobo": "https://static.wikia.nocookie.net/marvel_dc/images/9/90/Justice_League_Vol_2_23.2_Lobo_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20130911185531",
    "Clayface": "https://static.wikia.nocookie.net/marvel_dc/images/1/18/Batman_The_Dark_Knight_Vol_2_23.3_Clayface_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20130918210941",
    "Trigon": "https://static.wikia.nocookie.net/marvel_dc/images/c/c6/Raven_Daughter_of_Darkness_Vol_1_2_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20180228183317",
    "Mongul": "https://static.wikia.nocookie.net/marvel_dc/images/a/a2/Batman_Superman_Vol_1_6_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20131203202624",
    "Atrocitus": "https://static.wikia.nocookie.net/marvel_dc/images/5/59/Red_Lanterns_Vol_1_10_Textless.jpg/revision/latest/scale-to-width-down/400?cb=20120606171351"
  },
  "minecraft": {
    "Steve": "https://minecraft.wiki/images/thumb/Steve_%28classic%29_JE6.png/400px-Steve_%28classic%29_JE6.png?c0d48",
    "Alex": "https://minecraft.wiki/images/thumb/Alex_%28slim%29_JE3.png/400px-Alex_%28slim%29_JE3.png?baaf0",
    "Ender Dragon": "https://minecraft.wiki/images/Ender_Dragon.gif?fca41",
    "Wither": "https://minecraft.wiki/images/thumb/Wither_JE2_BE2.png/400px-Wither_JE2_BE2.png?18bf8",
    "Warden": "https://minecraft.wiki/images/Warden.gif?d0f99",
    "Creeper": "https://minecraft.wiki/images/thumb/Creeper_JE3_BE1.png/400px-Creeper_JE3_BE1.png?40005",
    "Enderman": "https://minecraft.wiki/images/thumb/Enderman_JE3.png/400px-Enderman_JE3.png?c6308",
    "Zombie": "https://minecraft.wiki/images/Zombie_JE5_BE2.png?d709c",
    "Skeleton": "https://minecraft.wiki/images/thumb/Lefthandedskeleton.png/400px-Lefthandedskeleton.png?2221f",
    "Spider": "https://minecraft.wiki/images/thumb/Spider_JE5_BE4.png/400px-Spider_JE5_BE4.png?b090e",
    "Witch": "https://minecraft.wiki/images/thumb/Witch_JE4.png/400px-Witch_JE4.png?731d4",
    "Pillager": "https://minecraft.wiki/images/thumb/Pillager_JE3.png/400px-Pillager_JE3.png?22662",
    "Evoker": "https://minecraft.wiki/images/thumb/Evoker_Summoning_Vexes.png/400px-Evoker_Summoning_Vexes.png?15d33",
    "Vindicator": "https://minecraft.wiki/images/thumb/Vindicator_attacking.png/400px-Vindicator_attacking.png?9b581",
    "Ravager": "https://minecraft.wiki/images/thumb/Ravager_JE1.png/400px-Ravager_JE1.png?55aae",
    "Vex": "https://minecraft.wiki/images/thumb/Vex_JE4.gif/400px-Vex_JE4.gif?da166",
    "Iron Golem": "https://minecraft.wiki/images/thumb/Iron_Golem_JE2_BE2.png/400px-Iron_Golem_JE2_BE2.png?2cd73",
    "Snow Golem": "https://minecraft.wiki/images/thumb/Snow_Golem_JE2_BE2.png/400px-Snow_Golem_JE2_BE2.png?23125",
    "Villager": "https://minecraft.wiki/images/thumb/Plains_Villager_Base_JE2.png/400px-Plains_Villager_Base_JE2.png?a2fcc",
    "Wolf": "https://minecraft.wiki/images/thumb/Wolf_JE2_BE2.png/400px-Wolf_JE2_BE2.png?ee46e",
    "Ghast": "https://minecraft.wiki/images/thumb/Ghast_JE3_BE3.gif/400px-Ghast_JE3_BE3.gif?ae9fb",
    "Blaze": "https://minecraft.wiki/images/Blaze_JE2.gif?29f6f",
    "Wither Skeleton": "https://minecraft.wiki/images/thumb/Wither_Skeleton_JE4_BE3.png/400px-Wither_Skeleton_JE4_BE3.png?9c107",
    "Piglin": "https://minecraft.wiki/images/thumb/Piglin_JE1.png/400px-Piglin_JE1.png?a498e",
    "Piglin Brute": "https://minecraft.wiki/images/thumb/Piglin_Brute_JE1.png/400px-Piglin_Brute_JE1.png?5d4a0",
    "Zombified Piglin": "https://minecraft.wiki/images/thumb/Zombified_Piglin_JE9.png/400px-Zombified_Piglin_JE9.png?7872f",
    "Hoglin": "https://minecraft.wiki/images/thumb/Hoglin_JE3.png/400px-Hoglin_JE3.png?65eaa",
    "Magma Cube": "https://minecraft.wiki/images/thumb/Magma_Cube_JE2_BE2.png/400px-Magma_Cube_JE2_BE2.png?dc507",
    "Guardian": "https://minecraft.wiki/images/Guardian_JE2_BE2.gif?19e5a",
    "Elder Guardian": "https://minecraft.wiki/images/Elder_Guardian_JE2_BE2.gif?99f67",
    "Drowned": "https://minecraft.wiki/images/thumb/Drowned_JE2.png/400px-Drowned_JE2.png?408ba",
    "Shulker": "https://minecraft.wiki/images/Shulker_JE1_BE1.png?02a87",
    "Phantom": "https://minecraft.wiki/images/Phantom_JE2.gif?ed906",
    "Slime": "https://minecraft.wiki/images/thumb/Slime_JE3_BE2.png/400px-Slime_JE3_BE2.png?5b6a7",
    "Silverfish": "https://minecraft.wiki/images/thumb/Silverfish_JE1_BE1.gif/400px-Silverfish_JE1_BE1.gif?d40a7",
    "Breeze": "https://minecraft.wiki/images/Breeze_BE1_JE2.webp?87e5c",
    "Bogged": "https://minecraft.wiki/images/Bogged_JE2_BE2.png?55cb9",
    "Creaking": "https://minecraft.wiki/images/Creaking_JE1_BE1.png?1a8ab",
    "Allay": "https://minecraft.wiki/images/Allay_JE2_BE2.gif?aca63",
    "Axolotl": "https://minecraft.wiki/images/thumb/Axolotl_Idle_Floor_Underwater.gif/400px-Axolotl_Idle_Floor_Underwater.gif?20bba",
    "Bee": "https://minecraft.wiki/images/thumb/Baby_Bee_JE2.gif/400px-Baby_Bee_JE2.gif?693e6",
    "Polar Bear": "https://minecraft.wiki/images/thumb/Polar_Bear_JE2_BE2.png/400px-Polar_Bear_JE2_BE2.png?29c45",
    "Goat": "https://minecraft.wiki/images/thumb/Goat_%28two_horns%29_JE1_BE1.png/400px-Goat_%28two_horns%29_JE1_BE1.png?a5c0c",
    "Fox": "https://minecraft.wiki/images/thumb/Fox_JE1_BE1.png/400px-Fox_JE1_BE1.png?ebd36",
    "Dolphin": "https://minecraft.wiki/images/thumb/Dolphin.gif/400px-Dolphin.gif?2581a",
    "Panda": "https://minecraft.wiki/images/thumb/Panda_JE1_BE1.png/400px-Panda_JE1_BE1.png?31d00",
    "Llama": "https://minecraft.wiki/images/thumb/White_Llama_JE2_BE2.png/400px-White_Llama_JE2_BE2.png?c9d61",
    "Sniffer": "https://minecraft.wiki/images/thumb/Sniffer_sniffsniff.gif/400px-Sniffer_sniffsniff.gif?1e613",
    "Cat": "https://minecraft.wiki/images/thumb/Jellie_Cat.png/400px-Jellie_Cat.png?e5d99",
    "Parrot": "https://minecraft.wiki/images/thumb/Red_Parrot_JE1_BE1.png/400px-Red_Parrot_JE1_BE1.png?90904",
    "Herobrine": "https://minecraft.wiki/images/thumb/Herobrine.png/400px-Herobrine.png?bc881"
  },
  "smash": {
    "Mario": "https://www.smashbros.com/assets_v2/img/fighter/mario/main.png",
    "Donkey Kong": "https://www.smashbros.com/assets_v2/img/fighter/donkey_kong/main.png",
    "Link": "https://www.smashbros.com/assets_v2/img/fighter/link/main.png",
    "Samus": "https://www.smashbros.com/assets_v2/img/fighter/samus/main.png",
    "Dark Samus": "https://www.smashbros.com/assets_v2/img/fighter/dark_samus/main.png",
    "Yoshi": "https://www.smashbros.com/assets_v2/img/fighter/yoshi/main.png",
    "Kirby": "https://www.smashbros.com/assets_v2/img/fighter/kirby/main.png",
    "Fox": "https://www.smashbros.com/assets_v2/img/fighter/fox/main.png",
    "Pikachu": "https://www.smashbros.com/assets_v2/img/fighter/pikachu/main.png",
    "Luigi": "https://www.smashbros.com/assets_v2/img/fighter/luigi/main.png",
    "Ness": "https://www.smashbros.com/assets_v2/img/fighter/ness/main.png",
    "Captain Falcon": "https://www.smashbros.com/assets_v2/img/fighter/captain_falcon/main.png",
    "Jigglypuff": "https://www.smashbros.com/assets_v2/img/fighter/jigglypuff/main.png",
    "Peach": "https://www.smashbros.com/assets_v2/img/fighter/peach/main.png",
    "Daisy": "https://www.smashbros.com/assets_v2/img/fighter/daisy/main.png",
    "Bowser": "https://www.smashbros.com/assets_v2/img/fighter/bowser/main.png",
    "Ice Climbers": "https://www.smashbros.com/assets_v2/img/fighter/ice_climbers/main.png",
    "Sheik": "https://www.smashbros.com/assets_v2/img/fighter/sheik/main.png",
    "Zelda": "https://www.smashbros.com/assets_v2/img/fighter/zelda/main.png",
    "Dr. Mario": "https://www.smashbros.com/assets_v2/img/fighter/dr_mario/main.png",
    "Pichu": "https://www.smashbros.com/assets_v2/img/fighter/pichu/main.png",
    "Falco": "https://www.smashbros.com/assets_v2/img/fighter/falco/main.png",
    "Marth": "https://www.smashbros.com/assets_v2/img/fighter/marth/main.png",
    "Lucina": "https://www.smashbros.com/assets_v2/img/fighter/lucina/main.png",
    "Young Link": "https://www.smashbros.com/assets_v2/img/fighter/young_link/main.png",
    "Ganondorf": "https://www.smashbros.com/assets_v2/img/fighter/ganondorf/main.png",
    "Mewtwo": "https://www.smashbros.com/assets_v2/img/fighter/mewtwo/main.png",
    "Roy": "https://www.smashbros.com/assets_v2/img/fighter/roy/main.png",
    "Chrom": "https://www.smashbros.com/assets_v2/img/fighter/chrom/main.png",
    "Mr. Game & Watch": "https://www.smashbros.com/assets_v2/img/fighter/mr_game_and_watch/main.png",
    "Meta Knight": "https://www.smashbros.com/assets_v2/img/fighter/meta_knight/main.png",
    "Pit": "https://www.smashbros.com/assets_v2/img/fighter/pit/main.png",
    "Dark Pit": "https://www.smashbros.com/assets_v2/img/fighter/dark_pit/main.png",
    "Zero Suit Samus": "https://www.smashbros.com/assets_v2/img/fighter/zero_suit_samus/main.png",
    "Wario": "https://www.smashbros.com/assets_v2/img/fighter/wario/main.png",
    "Snake": "https://www.smashbros.com/assets_v2/img/fighter/snake/main.png",
    "Ike": "https://www.smashbros.com/assets_v2/img/fighter/ike/main.png",
    "Pokémon Trainer": "https://www.smashbros.com/assets_v2/img/fighter/pokemon_trainer/main.png",
    "Diddy Kong": "https://www.smashbros.com/assets_v2/img/fighter/diddy_kong/main.png",
    "Lucas": "https://www.smashbros.com/assets_v2/img/fighter/lucas/main.png",
    "Sonic": "https://www.smashbros.com/assets_v2/img/fighter/sonic/main.png",
    "King Dedede": "https://www.smashbros.com/assets_v2/img/fighter/king_dedede/main.png",
    "Olimar": "https://www.smashbros.com/assets_v2/img/fighter/olimar/main.png",
    "Lucario": "https://www.smashbros.com/assets_v2/img/fighter/lucario/main.png",
    "R.O.B.": "https://www.smashbros.com/assets_v2/img/fighter/rob/main.png",
    "Toon Link": "https://www.smashbros.com/assets_v2/img/fighter/toon_link/main.png",
    "Wolf": "https://www.smashbros.com/assets_v2/img/fighter/wolf/main.png",
    "Villager": "https://www.smashbros.com/assets_v2/img/fighter/villager/main.png",
    "Mega Man": "https://www.smashbros.com/assets_v2/img/fighter/mega_man/main.png",
    "Wii Fit Trainer": "https://www.smashbros.com/assets_v2/img/fighter/wii_fit_trainer/main.png",
    "Rosalina & Luma": "https://www.smashbros.com/assets_v2/img/fighter/rosalina_and_luma/main.png",
    "Little Mac": "https://www.smashbros.com/assets_v2/img/fighter/little_mac/main.png",
    "Greninja": "https://www.smashbros.com/assets_v2/img/fighter/greninja/main.png",
    "Palutena": "https://www.smashbros.com/assets_v2/img/fighter/palutena/main.png",
    "Pac-Man": "https://www.smashbros.com/assets_v2/img/fighter/pac_man/main.png",
    "Robin": "https://www.smashbros.com/assets_v2/img/fighter/robin/main.png",
    "Shulk": "https://www.smashbros.com/assets_v2/img/fighter/shulk/main.png",
    "Bowser Jr.": "https://www.smashbros.com/assets_v2/img/fighter/bowser_jr/main.png",
    "Duck Hunt": "https://www.smashbros.com/assets_v2/img/fighter/duck_hunt/main.png",
    "Ryu": "https://www.smashbros.com/assets_v2/img/fighter/ryu/main.png",
    "Ken": "https://www.smashbros.com/assets_v2/img/fighter/ken/main.png",
    "Cloud": "https://www.smashbros.com/assets_v2/img/fighter/cloud/main.png",
    "Corrin": "https://www.smashbros.com/assets_v2/img/fighter/corrin/main.png",
    "Bayonetta": "https://www.smashbros.com/assets_v2/img/fighter/bayonetta/main.png",
    "Inkling": "https://www.smashbros.com/assets_v2/img/fighter/inkling/main.png",
    "Ridley": "https://www.smashbros.com/assets_v2/img/fighter/ridley/main.png",
    "Simon": "https://www.smashbros.com/assets_v2/img/fighter/simon/main.png",
    "Richter": "https://www.smashbros.com/assets_v2/img/fighter/richter/main.png",
    "King K. Rool": "https://www.smashbros.com/assets_v2/img/fighter/king_k_rool/main.png",
    "Isabelle": "https://www.smashbros.com/assets_v2/img/fighter/isabelle/main.png",
    "Incineroar": "https://www.smashbros.com/assets_v2/img/fighter/incineroar/main.png",
    "Piranha Plant": "https://www.smashbros.com/assets_v2/img/fighter/piranha_plant/main.png",
    "Joker": "https://www.smashbros.com/assets_v2/img/fighter/joker/main.png",
    "Hero": "https://www.smashbros.com/assets_v2/img/fighter/dq_hero/main.png",
    "Banjo & Kazooie": "https://www.smashbros.com/assets_v2/img/fighter/banjo_and_kazooie/main.png",
    "Terry": "https://www.smashbros.com/assets_v2/img/fighter/terry/main.png",
    "Byleth": "https://www.smashbros.com/assets_v2/img/fighter/byleth/main.png",
    "Min Min": "https://www.smashbros.com/assets_v2/img/fighter/minmin/main.png",
    "Steve": "https://www.smashbros.com/assets_v2/img/fighter/steve/main.png",
    "Sephiroth": "https://www.smashbros.com/assets_v2/img/fighter/sephiroth/main.png",
    "Pyra & Mythra": "https://www.smashbros.com/assets_v2/img/fighter/pyra/main.png",
    "Kazuya": "https://www.smashbros.com/assets_v2/img/fighter/kazuya/main.png",
    "Sora": "https://www.smashbros.com/assets_v2/img/fighter/sora/main.png"
  }
};
