/* Character pictures, keyed by world then name. Generated from the Game of Thrones
   and Marvel Fandom wikis and Riot's Data Dragon. A character with no entry here
   gets a lettered placeholder instead, so new characters can be added freely. */

window.CHARACTER_IMAGES = {
  "westeros": {
    "Jon Snow": "https://static.wikia.nocookie.net/gameofthrones/images/d/d0/JonSnow8x06.PNG/revision/latest/scale-to-width-down/400",
    "Daenerys Targaryen": "https://static.wikia.nocookie.net/gameofthrones/images/4/4f/Daenerys_Season_8.jpg/revision/latest/scale-to-width-down/400",
    "Tyrion Lannister": "https://static.wikia.nocookie.net/gameofthrones/images/9/95/HandoftheKingTyrionLannister.PNG/revision/latest/scale-to-width-down/400",
    "Cersei Lannister": "https://static.wikia.nocookie.net/gameofthrones/images/b/b0/CERSEIBATTLEOFKINGSLANDING.PNG/revision/latest/scale-to-width-down/400",
    "Jaime Lannister": "https://static.wikia.nocookie.net/gameofthrones/images/5/51/JaimeLannisterSeason8.PNG/revision/latest/scale-to-width-down/400",
    "Tywin Lannister": "https://static.wikia.nocookie.net/gameofthrones/images/7/71/Tywin_Lannister_4x08.jpg/revision/latest/scale-to-width-down/400",
    "Arya Stark": "https://static.wikia.nocookie.net/gameofthrones/images/b/be/AryaShipIronThrone.PNG/revision/latest/scale-to-width-down/400",
    "Sansa Stark": "https://static.wikia.nocookie.net/gameofthrones/images/6/63/QueenSansa.PNG/revision/latest/scale-to-width-down/400",
    "Bran Stark": "https://static.wikia.nocookie.net/gameofthrones/images/8/81/KingBran.PNG/revision/latest/scale-to-width-down/400",
    "Ned Stark": "https://static.wikia.nocookie.net/gameofthrones/images/3/34/Eddard_Stark.jpg/revision/latest/scale-to-width-down/400",
    "Robb Stark": "https://static.wikia.nocookie.net/gameofthrones/images/5/50/S3E9_Robb_Stark_main.jpg/revision/latest/scale-to-width-down/400",
    "Catelyn Stark": "https://static.wikia.nocookie.net/gameofthrones/images/d/d8/CatelynS3Promo.jpg/revision/latest/scale-to-width-down/400",
    "Theon Greyjoy": "https://static.wikia.nocookie.net/gameofthrones/images/7/78/TheonS8E1.PNG/revision/latest/scale-to-width-down/400",
    "Yara Greyjoy": "https://static.wikia.nocookie.net/gameofthrones/images/a/a8/Game_of_thrones_6x5_yara_promo.jpg/revision/latest/scale-to-width-down/400",
    "Euron Greyjoy": "https://static.wikia.nocookie.net/gameofthrones/images/f/fc/Euron-Profile.PNG/revision/latest/scale-to-width-down/400",
    "Sandor Clegane": "https://static.wikia.nocookie.net/gameofthrones/images/b/b5/SandorConfrontsGregor.PNG/revision/latest/scale-to-width-down/400",
    "Gregor Clegane": "https://static.wikia.nocookie.net/gameofthrones/images/8/81/GregorGregorLightenedProfile.png/revision/latest/scale-to-width-down/400",
    "Brienne of Tarth": "https://static.wikia.nocookie.net/gameofthrones/images/a/a9/S8_Brienne_Profil.jpg/revision/latest/scale-to-width-down/400",
    "Podrick Payne": "https://static.wikia.nocookie.net/gameofthrones/images/2/22/Podrick8x01.PNG/revision/latest/scale-to-width-down/400",
    "Bronn": "https://static.wikia.nocookie.net/gameofthrones/images/f/f5/Bronn_S8E6.png/revision/latest/scale-to-width-down/400",
    "Samwell Tarly": "https://static.wikia.nocookie.net/gameofthrones/images/8/8f/Maester_Sam.png/revision/latest/scale-to-width-down/400",
    "Jorah Mormont": "https://static.wikia.nocookie.net/gameofthrones/images/2/26/Winterfell_ep_Jorah_s8.jpg/revision/latest/scale-to-width-down/400",
    "Davos Seaworth": "https://static.wikia.nocookie.net/gameofthrones/images/9/9d/DAVOSINFOBOXBELLS.PNG/revision/latest/scale-to-width-down/400",
    "Stannis Baratheon": "https://static.wikia.nocookie.net/gameofthrones/images/2/2f/StannisNew.png/revision/latest/scale-to-width-down/400",
    "Robert Baratheon": "https://static.wikia.nocookie.net/gameofthrones/images/4/43/Robert_crop.png/revision/latest/scale-to-width-down/400",
    "Joffrey Baratheon": "https://static.wikia.nocookie.net/gameofthrones/images/2/25/Joffrey_Season_4_Episode_2_TLATR.jpg/revision/latest/scale-to-width-down/400",
    "Melisandre": "https://static.wikia.nocookie.net/gameofthrones/images/0/07/Melisandre_%28The_Queen%27s_Justice%29.png/revision/latest/scale-to-width-down/400",
    "Petyr Baelish": "https://static.wikia.nocookie.net/gameofthrones/images/9/9f/Profile-Littlefinger.png/revision/latest/scale-to-width-down/400",
    "Varys": "https://static.wikia.nocookie.net/gameofthrones/images/f/ff/Varys8x05Dragonstone.PNG/revision/latest/scale-to-width-down/400",
    "Oberyn Martell": "https://static.wikia.nocookie.net/gameofthrones/images/4/44/Oberyn-Martell-house-martell_s3.jpg/revision/latest/scale-to-width-down/400",
    "Ellaria Sand": "https://static.wikia.nocookie.net/gameofthrones/images/4/4c/Ellaria_Sand_The_End.png/revision/latest/scale-to-width-down/400",
    "Tormund Giantsbane": "https://static.wikia.nocookie.net/gameofthrones/images/9/97/Tormund_Profile.PNG/revision/latest/scale-to-width-down/400",
    "Ygritte": "https://static.wikia.nocookie.net/gameofthrones/images/2/28/Ygritte-promotionals4pic.jpg/revision/latest/scale-to-width-down/400",
    "The Night King": "https://static.wikia.nocookie.net/gameofthrones/images/1/1f/Night_King_BTW.jpg/revision/latest/scale-to-width-down/400",
    "Khal Drogo": "https://static.wikia.nocookie.net/gameofthrones/images/2/21/Khal_Drogo_infobox_promo.jpg/revision/latest/scale-to-width-down/400",
    "Grey Worm": "https://static.wikia.nocookie.net/gameofthrones/images/7/77/Grey-Worm-S8E5.png/revision/latest/scale-to-width-down/400",
    "Missandei": "https://static.wikia.nocookie.net/gameofthrones/images/d/de/Missandei8X04.PNG/revision/latest/scale-to-width-down/400",
    "Margaery Tyrell": "https://static.wikia.nocookie.net/gameofthrones/images/b/b5/Margaery_Tyrell_S6.png/revision/latest/scale-to-width-down/400",
    "Olenna Tyrell": "https://static.wikia.nocookie.net/gameofthrones/images/f/f2/OlennaS7E3.png/revision/latest/scale-to-width-down/400",
    "Ramsay Bolton": "https://static.wikia.nocookie.net/gameofthrones/images/d/d2/Ramsay_S06E09_RESZIED_FOR_INFOBOX.jpg/revision/latest/scale-to-width-down/400",
    "Jaqen H'ghar": "https://static.wikia.nocookie.net/gameofthrones/images/d/da/The_Door_Jaqen_infobox.jpg/revision/latest/scale-to-width-down/400",
    "Gendry": "https://static.wikia.nocookie.net/gameofthrones/images/7/7b/GendryBaratheon.png/revision/latest/scale-to-width-down/400",
    "Hodor": "https://static.wikia.nocookie.net/gameofthrones/images/1/18/Season_6_hodor_main.jpg/revision/latest/scale-to-width-down/400",
    "Beric Dondarrion": "https://static.wikia.nocookie.net/gameofthrones/images/4/44/803_Beric_Promo_Crop.png/revision/latest/scale-to-width-down/400",
    "Barristan Selmy": "https://static.wikia.nocookie.net/gameofthrones/images/1/1f/Barristan_Selmy_Sons_of_the_Harpy.jpg/revision/latest/scale-to-width-down/400",
    "Daario Naharis": "https://static.wikia.nocookie.net/gameofthrones/images/d/d8/Daario-s6e4.jpg/revision/latest/scale-to-width-down/400",
    "Rhaenyra Targaryen": "https://static.wikia.nocookie.net/gameofthrones/images/4/40/Rhaenyra_308.png/revision/latest/scale-to-width-down/400",
    "Daemon Targaryen": "https://static.wikia.nocookie.net/gameofthrones/images/d/d5/Daemon_S3_Profile.png/revision/latest/scale-to-width-down/400",
    "Viserys I Targaryen": "https://static.wikia.nocookie.net/gameofthrones/images/3/38/Viserys_I_Targaryen_Official_Guide.jpg/revision/latest/scale-to-width-down/400",
    "Alicent Hightower": "https://static.wikia.nocookie.net/gameofthrones/images/1/18/AlicentASfASInfobox.PNG/revision/latest/scale-to-width-down/400",
    "Otto Hightower": "https://static.wikia.nocookie.net/gameofthrones/images/b/b8/Otto_Hightower-302.jpg/revision/latest/scale-to-width-down/400",
    "Aegon II Targaryen": "https://static.wikia.nocookie.net/gameofthrones/images/d/da/Aegon_302_Profile.jpg/revision/latest/scale-to-width-down/400",
    "Aemond Targaryen": "https://static.wikia.nocookie.net/gameofthrones/images/6/63/Aemond_Targaryen-301.jpg/revision/latest/scale-to-width-down/400",
    "Helaena Targaryen": "https://static.wikia.nocookie.net/gameofthrones/images/c/c8/Helaena_Targaryen-301.jpg/revision/latest/scale-to-width-down/400",
    "Criston Cole": "https://static.wikia.nocookie.net/gameofthrones/images/b/b6/Criston_Cole-306.jpg/revision/latest/scale-to-width-down/400",
    "Corlys Velaryon": "https://static.wikia.nocookie.net/gameofthrones/images/5/5a/Corlys_Velaryon_S2.jpg/revision/latest/scale-to-width-down/400",
    "Rhaenys Targaryen": "https://static.wikia.nocookie.net/gameofthrones/images/2/21/Rhaenys_Targaryen1.png/revision/latest/scale-to-width-down/400",
    "Jacaerys Velaryon": "https://static.wikia.nocookie.net/gameofthrones/images/5/5f/Jacaerys-206.jpeg/revision/latest/scale-to-width-down/400",
    "Baela Targaryen": "https://static.wikia.nocookie.net/gameofthrones/images/8/8d/BaelaTargaryen2x03.PNG/revision/latest/scale-to-width-down/400",
    "Larys Strong": "https://static.wikia.nocookie.net/gameofthrones/images/7/76/Larys_Strong_S2.jpg/revision/latest/scale-to-width-down/400",
    "Mysaria": "https://static.wikia.nocookie.net/gameofthrones/images/7/78/305_Mysaria_Still.jpg/revision/latest/scale-to-width-down/400",
    "Cregan Stark": "https://static.wikia.nocookie.net/gameofthrones/images/8/83/Cregan-portrait.png/revision/latest/scale-to-width-down/400",
    "Alys Rivers": "https://static.wikia.nocookie.net/gameofthrones/images/4/42/Alys_Rivers-304.jpg/revision/latest/scale-to-width-down/400",
    "Drogon": "https://static.wikia.nocookie.net/gameofthrones/images/8/8f/DrogonWinterfell8x01.PNG/revision/latest/scale-to-width-down/400",
    "Rhaegal": "https://static.wikia.nocookie.net/gameofthrones/images/5/54/RhaegalPostFlight.PNG/revision/latest/scale-to-width-down/400",
    "Viserion": "https://static.wikia.nocookie.net/gameofthrones/images/0/0e/Viserion_Dragonstone.png/revision/latest/scale-to-width-down/400",
    "Vhagar": "https://static.wikia.nocookie.net/gameofthrones/images/e/ef/Vhagar-302.jpg/revision/latest/scale-to-width-down/400",
    "Caraxes": "https://static.wikia.nocookie.net/gameofthrones/images/0/0e/Caraxes_Official_Guide.png/revision/latest/scale-to-width-down/400",
    "Meleys": "https://static.wikia.nocookie.net/gameofthrones/images/d/d8/Meleys-204.jpg/revision/latest/scale-to-width-down/400",
    "Sunfyre": "https://static.wikia.nocookie.net/gameofthrones/images/e/e0/Sunfyre_307.png/revision/latest/scale-to-width-down/400",
    "Ghost": "https://static.wikia.nocookie.net/gameofthrones/images/9/94/804_Ghost_Profile.png/revision/latest/scale-to-width-down/400",
    "Nymeria": "https://static.wikia.nocookie.net/gameofthrones/images/5/54/Nymeria-S7.png/revision/latest/scale-to-width-down/400"
  },
  "marvel": {
    "Iron Man": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/9/9d/Iron_Man_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Captain America": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/9/9d/Captain_America_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Thor": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/2/2b/Thor_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Hulk": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/2/29/Hulk_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Black Widow": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/3/3f/Black_Widow_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Hawkeye": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/5/5b/Hawkeye_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Spider-Man": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/4/41/Spider-Man_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Doctor Strange": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/b/b2/Doctor_Strange_MoM_Profile.jpeg/revision/latest/scale-to-width-down/400",
    "Black Panther": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/9/93/Black_Panther_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Captain Marvel": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/3/3d/Captain_Marvel_Profile.png/revision/latest/scale-to-width-down/400",
    "Scarlet Witch": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/6/60/Scarlet_Witch_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Vision": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/6/6e/Vision_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Ant-Man": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/4/46/Ant-Man_Infobox.png/revision/latest/scale-to-width-down/400",
    "The Wasp": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/2/22/Wasp_Quantumania.jpg/revision/latest/scale-to-width-down/400",
    "Falcon": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/3/3d/Falcon_Infobox.png/revision/latest/scale-to-width-down/400",
    "Winter Soldier": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/2/21/Winter_Soldier_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "War Machine": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/7/77/WarMachine-EndgameProfile.jpg/revision/latest/scale-to-width-down/400",
    "Star-Lord": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/6/6c/Star-Lord_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Gamora": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/7/70/Gamora_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Drax": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/c/cd/Drax_Vol._3.jpg/revision/latest/scale-to-width-down/400",
    "Rocket": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/3/30/Rocket_Vol._3.jpg/revision/latest/scale-to-width-down/400",
    "Groot": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/5/57/Groot_Infobox.png/revision/latest/scale-to-width-down/400",
    "Mantis": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/2/27/Mantis_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Nebula": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/3/37/Nebula_Vol._3.jpg/revision/latest/scale-to-width-down/400",
    "Thanos": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/2/27/Thanos_Infobox.png/revision/latest/scale-to-width-down/400",
    "Loki": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/b/b5/Loki_Infobox.png/revision/latest/scale-to-width-down/400",
    "Ultron": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/6/6a/Ultron_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Hela": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/a/ae/Hela_Infobox.png/revision/latest/scale-to-width-down/400",
    "Wolverine": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/7/7c/Wolverine_Infobox.png/revision/latest/scale-to-width-down/400",
    "Deadpool": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/a/ad/Deadpool_Infobox.png/revision/latest/scale-to-width-down/400",
    "Professor X": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/0/06/Professor_X_Infobox.png/revision/latest/scale-to-width-down/400",
    "Magneto": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/4/41/Magneto_Infobox.png/revision/latest/scale-to-width-down/400",
    "Cyclops": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/3/3d/Cyclops_Infobox.png/revision/latest/scale-to-width-down/400",
    "Gambit": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/a/ab/Gambit_Infobox.png/revision/latest/scale-to-width-down/400",
    "Mystique": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/f/f8/Mystique_Infobox.jpeg/revision/latest/scale-to-width-down/400",
    "Juggernaut": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/0/07/Juggernaut.png/revision/latest/scale-to-width-down/400",
    "Nightcrawler": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/5/53/Nightcrawler_Infobox.jpeg/revision/latest/scale-to-width-down/400",
    "Silver Surfer": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/6/65/Shalla-Bal_%28Silver_Surfer%29_Infobox.png/revision/latest/scale-to-width-down/400",
    "Galactus": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/a/a7/Galactus.png/revision/latest/scale-to-width-down/400",
    "Doctor Doom": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/0/07/Doctor_Doom_Infobox.png/revision/latest/scale-to-width-down/400",
    "Mister Fantastic": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/9/9f/Mister_Fantastic_Infobox.png/revision/latest/scale-to-width-down/400",
    "Invisible Woman": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/6/69/Invisible_Woman_Infobox.png/revision/latest/scale-to-width-down/400",
    "Human Torch": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/b/b8/Human_Torch_Infobox.png/revision/latest/scale-to-width-down/400",
    "The Thing": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/2/2a/Thing_Infobox.png/revision/latest/scale-to-width-down/400",
    "Ghost Rider": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/8/80/Ghost_Rider_RR.jpg/revision/latest/scale-to-width-down/400",
    "Daredevil": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/d/d7/Daredevil_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "The Punisher": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/1/1c/Punisher_Infobox.png/revision/latest/scale-to-width-down/400",
    "Moon Knight": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/e/ea/Moon_Knight_Poster_Textless.png/revision/latest/scale-to-width-down/400",
    "Ms. Marvel": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/2/22/Ms._Marvel_Infobox.png/revision/latest/scale-to-width-down/400",
    "She-Hulk": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/5/5a/She-Hulk_-_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Shang-Chi": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/4/40/Shang-Chi_Profile.jpg/revision/latest/scale-to-width-down/400",
    "Carnage": "https://static.wikia.nocookie.net/marveldatabase/images/9/98/Carnage_Vol_4_1_Mastrazzo_Variant_Textless.jpg/revision/latest/scale-to-width-down/400",
    "Green Goblin": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/3/39/Green_Goblin_Infobox.png/revision/latest/scale-to-width-down/400",
    "Doctor Octopus": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/1/15/Doctor_Octopus_Infobox.png/revision/latest/scale-to-width-down/400",
    "Kang the Conqueror": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/e/e4/Kang_the_Conqueror_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Red Skull": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/6/6d/Red_Skull_Infobox.png/revision/latest/scale-to-width-down/400",
    "Namor": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/8/89/Namor_Profile.png/revision/latest/scale-to-width-down/400",
    "Adam Warlock": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/0/08/Adam_Warlock_Infobox.png/revision/latest/scale-to-width-down/400",
    "Nick Fury": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/a/a3/Nick_Fury_Infobox.png/revision/latest/scale-to-width-down/400",
    "Kingpin": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/9/9c/Kingpin_Infobox.jpg/revision/latest/scale-to-width-down/400",
    "Black Bolt": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/1/18/Black_Bolt.jpg/revision/latest/scale-to-width-down/400",
    "Okoye": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/2/25/Black_Panther_Wakanda_Forever_poster_024_Textless.jpg/revision/latest/scale-to-width-down/400",
    "Valkyrie": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/d/d8/Valkyrie_in_LoveAndThunder_Poster.png/revision/latest/scale-to-width-down/400",
    "Squirrel Girl": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/0/01/Squirrel_Girl.png/revision/latest/scale-to-width-down/400",
    "Howard the Duck": "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/d/d0/Howard_duck.png/revision/latest/scale-to-width-down/400",
    "Storm": "https://static.wikia.nocookie.net/marveldatabase/images/9/9a/Storm_Vol_5_7_Textless.jpg/revision/latest/scale-to-width-down/400",
    "Phoenix": "https://static.wikia.nocookie.net/marveldatabase/images/6/64/Phoenix_Vol_1_11_Textless.jpg/revision/latest/scale-to-width-down/400",
    "Rogue": "https://static.wikia.nocookie.net/marveldatabase/images/b/bb/Uncanny_X-Men_Vol_6_34_Rogue_Virgin_Variant.jpg/revision/latest/scale-to-width-down/400",
    "Blade": "https://static.wikia.nocookie.net/marveldatabase/images/2/29/Blade_Vol_6_1_Textless.jpg/revision/latest/scale-to-width-down/400",
    "Venom": "https://static.wikia.nocookie.net/marveldatabase/images/b/b3/All-New_Venom_Vol_1_1_Lee_Virgin_Variant.jpg/revision/latest/scale-to-width-down/400"
  },
  "league": {
    "Ahri": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ahri_0.jpg",
    "Yasuo": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yasuo_0.jpg",
    "Yone": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yone_0.jpg",
    "Lee Sin": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/LeeSin_0.jpg",
    "Master Yi": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/MasterYi_0.jpg",
    "Irelia": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Irelia_0.jpg",
    "Akali": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Akali_0.jpg",
    "Shen": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Shen_0.jpg",
    "Zed": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zed_0.jpg",
    "Kennen": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kennen_0.jpg",
    "Jinx": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jinx_0.jpg",
    "Vi": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Vi_0.jpg",
    "Caitlyn": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Caitlyn_0.jpg",
    "Jayce": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jayce_0.jpg",
    "Viktor": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Viktor_0.jpg",
    "Ekko": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ekko_0.jpg",
    "Ezreal": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ezreal_0.jpg",
    "Heimerdinger": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Heimerdinger_0.jpg",
    "Singed": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Singed_0.jpg",
    "Warwick": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Warwick_0.jpg",
    "Lux": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lux_0.jpg",
    "Garen": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Garen_0.jpg",
    "Jarvan IV": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/JarvanIV_0.jpg",
    "Xin Zhao": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/XinZhao_0.jpg",
    "Sylas": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sylas_0.jpg",
    "Darius": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Darius_0.jpg",
    "Draven": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Draven_0.jpg",
    "Katarina": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Katarina_0.jpg",
    "Swain": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Swain_0.jpg",
    "LeBlanc": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Leblanc_0.jpg",
    "Sion": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sion_0.jpg",
    "Ashe": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ashe_0.jpg",
    "Sejuani": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sejuani_0.jpg",
    "Lissandra": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lissandra_0.jpg",
    "Braum": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Braum_0.jpg",
    "Tryndamere": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Tryndamere_0.jpg",
    "Ornn": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ornn_0.jpg",
    "Volibear": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Volibear_0.jpg",
    "Anivia": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Anivia_0.jpg",
    "Leona": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Leona_0.jpg",
    "Diana": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Diana_0.jpg",
    "Pantheon": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Pantheon_0.jpg",
    "Aphelios": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Aphelios_0.jpg",
    "Aurelion Sol": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/AurelionSol_0.jpg",
    "Miss Fortune": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/MissFortune_0.jpg",
    "Gangplank": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Gangplank_0.jpg",
    "Graves": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Graves_0.jpg",
    "Twisted Fate": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/TwistedFate_0.jpg",
    "Pyke": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Pyke_0.jpg",
    "Thresh": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Thresh_0.jpg",
    "Viego": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Viego_0.jpg",
    "Senna": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Senna_0.jpg",
    "Lucian": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lucian_0.jpg",
    "Azir": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Azir_0.jpg",
    "Nasus": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nasus_0.jpg",
    "Renekton": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Renekton_0.jpg",
    "Xerath": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Xerath_0.jpg",
    "Rammus": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rammus_0.jpg",
    "Aatrox": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Aatrox_0.jpg",
    "Kayle": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kayle_0.jpg",
    "Morgana": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Morgana_0.jpg",
    "Mordekaiser": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Mordekaiser_0.jpg",
    "Kai'Sa": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kaisa_0.jpg",
    "Vel'Koz": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Velkoz_0.jpg",
    "Bard": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Bard_0.jpg",
    "Nocturne": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nocturne_0.jpg",
    "Fiddlesticks": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiddlesticks_0.jpg",
    "Sett": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sett_0.jpg",
    "Teemo": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Teemo_0.jpg",
    "Yuumi": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yuumi_0.jpg",
    "Annie": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Annie_0.jpg",
    "Blitzcrank": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Blitzcrank_0.jpg",
    "Malphite": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Malphite_0.jpg",
    "Gwen": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Gwen_0.jpg"
  }
};
