/* Riftle — the answer list.

   Every answer is five letters and League of Legends adjacent: champions,
   items, monsters, places, runes, and the things people type in chat.
   The gloss is shown when the round ends, so keep it short and warm.

   Adding a word: append it anywhere. The daily order is a fixed shuffle of
   this array, seeded once — so the schedule is identical in every browser,
   but changing the list reshuffles which word lands on which day. Freeze the
   list if you ever want a published schedule to stay put. */

export const WORDS = [
  /* --- Champions ---------------------------------------- */
  ["AKALI", "the Rogue Assassin"],
  ["AMUMU", "the Sad Mummy"],
  ["ANNIE", "the Dark Child"],
  ["BRAND", "the Burning Vengeance"],
  ["BRAUM", "the Heart of the Freljord"],
  ["BRIAR", "the Restrained Hunger"],
  ["CORKI", "the Daring Bombardier"],
  ["DIANA", "Scorn of the Moon"],
  ["ELISE", "the Spider Queen"],
  ["FIORA", "the Grand Duelist"],
  ["GALIO", "the Colossus"],
  ["GAREN", "the Might of Demacia"],
  ["IVERN", "the Green Father"],
  ["JANNA", "the Storm's Fury"],
  ["JAYCE", "the Defender of Tomorrow"],
  ["KAISA", "Daughter of the Void"],
  ["KARMA", "the Enlightened One"],
  ["KAYLE", "the Righteous"],
  ["KENCH", "the other half of Tahm Kench, the River King"],
  ["LEONA", "the Radiant Dawn"],
  ["MILIO", "the Gentle Flame"],
  ["MUNDO", "Dr. Mundo goes where he pleases"],
  ["NASUS", "the Curator of the Sands"],
  ["NEEKO", "the Curious Chameleon"],
  ["NILAH", "the Joy Unbound"],
  ["POPPY", "Keeper of the Hammer"],
  ["QUINN", "Demacia's Wings"],
  ["RAKAN", "the Charmer"],
  ["RIVEN", "the Exile"],
  ["SENNA", "the Redeemer"],
  ["SHACO", "the Demon Jester"],
  ["SIVIR", "the Battle Mistress"],
  ["SWAIN", "the Noxian Grand General"],
  ["SYLAS", "the Unshackled"],
  ["TALON", "the Blade's Shadow"],
  ["TARIC", "the Shield of Valoran"],
  ["TEEMO", "the Swift Scout"],
  ["URGOT", "the Dreadnought"],
  ["VARUS", "the Arrow of Retribution"],
  ["VAYNE", "the Night Hunter"],
  ["VIEGO", "the Ruined King"],
  ["XAYAH", "the Rebel"],
  ["YASUO", "the Unforgiven"],
  ["YUUMI", "the Magical Cat"],
  ["ZIGGS", "the Hexplosives Expert"],

  /* --- Champions, as everyone actually types them -------- */
  ["BLITZ", "Blitzcrank, already winding up the hook"],
  ["MALPH", "Malphite, arriving from somewhere off screen"],
  ["MORDE", "Mordekaiser, and his little pocket dimension"],
  ["PANTH", "Pantheon, spear first"],
  ["TRIST", "Tristana, and a very large cannon"],
  ["TRYND", "Tryndamere, refusing to die on schedule"],

  /* --- The map, its monsters and its plants -------------- */
  ["ABYSS", "the Howling one, where ARAM lives"],
  ["BARON", "the buff worth throwing a game for"],
  ["BIRDS", "the raptor camp, in short"],
  ["BLAST", "the cone that launches you over a wall"],
  ["BLOOM", "the scryer's, revealing everything nearby"],
  ["BRUSH", "the bush, if you want to be formal about it"],
  ["CAMPS", "the jungle's monsters, all on a timer"],
  ["CLOUD", "the drake that makes you faster"],
  ["CRABS", "the scuttlers, and the vision they hand out"],
  ["CREEP", "creep score, or the thing you are killing"],
  ["DAISY", "Ivern's friend — large, gentle, effective"],
  ["DRAKE", "the dragon, in a hurry"],
  ["ELDER", "the dragon that ends games"],
  ["GOLEM", "what the blue buff camp used to be"],
  ["GROMP", "the big frog in the jungle"],
  ["GRUBS", "the voidlings that eat towers"],
  ["HONEY", "the fruit that heals you in the jungle"],
  ["KRUGS", "the rock camp nobody enjoys"],
  ["LANES", "top, mid and bot"],
  ["NEXUS", "the thing you are actually trying to break"],
  ["OCEAN", "the drake that heals you"],
  ["PLANT", "blast cones, honeyfruit and scryer's blooms"],
  ["PLATE", "turret plating — gold, in a hurry"],
  ["RIVER", "the middle of the map, where fights start"],
  ["SOULS", "four drakes and the game changes"],
  ["SPAWN", "where you go when it goes wrong"],
  ["SUPER", "the minion that arrives when an inhibitor falls"],
  ["TOTEM", "the warding kind — yellow, free, forgotten"],
  ["TOWER", "do not stand under it"],
  ["WALLS", "the ones you flash over"],
  ["WAVES", "freeze them, push them, crash them"],

  /* --- Places, lore and the things that live there ------- */
  ["BEARS", "Tibbers, Volibear, and Udyr in a bad mood"],
  ["CHILD", "Annie's title, and the bear that comes with it"],
  ["CROWN", "Viego's, and all the ruin that followed"],
  ["DEMON", "Shaco, Evelynn, Tahm Kench — take your pick"],
  ["EXILE", "Riven's title, carried on a broken sword"],
  ["FROST", "the Freljord, in one word"],
  ["GHOUL", "Yorick's, shambling out of a fresh grave"],
  ["GRAND", "Fiora's duelling, and the rank below challenger"],
  ["GREEN", "Ivern's fatherhood, and the jungle he keeps"],
  ["IONIA", "the land of balance and blades"],
  ["ISLES", "the Shadow Isles, still misty"],
  ["IXTAL", "the hidden elemental realm"],
  ["KINGS", "Viego ruined, Trundle trolls, Tahm rivers"],
  ["LIGHT", "the Firelights of Zaun, and Lux everywhere else"],
  ["MIGHT", "Garen's, of Demacia"],
  ["MISTS", "the black kind, drifting off the Shadow Isles"],
  ["MUMMY", "Amumu, still sad"],
  ["NIGHT", "Vayne hunts in it; Nocturne simply is it"],
  ["NOXUS", "the empire that takes what it wants"],
  ["ORDER", "the Kinkou — Shen's, and once Akali's"],
  ["QUEEN", "Elise's spiders, and Ashe's Freljord"],
  ["REBEL", "Xayah's title, and half her feathers"],
  ["ROBOT", "Blitzcrank, Orianna, and Viktor's ambition"],
  ["SANDS", "Shurima's, and Nasus who curates them"],
  ["SCORN", "Diana's, of the moon"],
  ["SHEEP", "what Lulu turns you into, mid-fight"],
  ["SILCO", "Zaun's quiet villain, from Arcane"],
  ["SNAKE", "Cassiopeia, from the waist down"],
  ["STARS", "Soraka's home, and the Guardians named for them"],
  ["STONE", "Malphite, and the mountain he brought"],
  ["STORM", "Janna's fury, and Volibear's weather"],
  ["TREES", "Maokai, and the saplings he keeps throwing"],
  ["TROLL", "Trundle's people, and a certain kind of teammate"],
  ["WINGS", "Quinn's, Xayah's, Rakan's, Kayle's"],
  ["YETIS", "Willump, carrying Nunu everywhere"],

  /* --- Summoner spells and runes ------------------------- */
  ["CHEAP", "cheap shot — true damage, from behind"],
  ["COMET", "Arcane Comet, for poking"],
  ["FLASH", "always on cooldown when you need it"],
  ["FLEET", "Fleet Footwork, for surviving lane"],
  ["GHOST", "move fast, hit nothing"],
  ["GRASP", "Grasp of the Undying, one stack at a time"],
  ["PHASE", "phase rush, and away you go"],
  ["PRESS", "press the attack"],
  ["SMITE", "the jungler's spell, and the steal button"],
  ["TEMPO", "lethal tempo, ramping up"],

  /* --- Items --------------------------------------------- */
  ["ANGEL", "Guardian Angel, and one more life"],
  ["ARMOR", "buy it when they are hitting you with sticks"],
  ["BLADE", "as in Blade of the Ruined King"],
  ["BOOTS", "buy them early, upgrade them late"],
  ["BUILD", "the items you meant to buy"],
  ["CHAIN", "as in chain vest, 800 gold of patience"],
  ["CLOAK", "Cloak of Agility, where crit begins"],
  ["COINS", "the ancient kind, gathering gold for supports"],
  ["CRITS", "the number that suddenly doubles"],
  ["DORAN", "blade, ring, or shield"],
  ["FANGS", "the serpent's, for shield-heavy teams"],
  ["FORCE", "as in Force of Nature"],
  ["GLYPH", "the old magic resist rune"],
  ["HASTE", "ability haste — the good kind of cooldown"],
  ["HEART", "as in Heartsteel"],
  ["HYDRA", "ravenous, titanic, or profane"],
  ["ITEMS", "six of them, if the game goes long enough"],
  ["LUCID", "the boots that shorten your cooldowns"],
  ["MAGIC", "as in magic resist"],
  ["MEJAI", "Mejai's Soulstealer, for the confident"],
  ["MERCS", "mercury's treads, for the crowd control"],
  ["PINKS", "pink wards, before they turned red"],
  ["QUINT", "a quintessence, from the old rune pages"],
  ["RELIC", "the shield the support starts with"],
  ["RYLAI", "Rylai's Crystal Scepter, slowing everything"],
  ["SEALS", "the old armour runes, bought a page at a time"],
  ["SHEEN", "a small item with a very large future"],
  ["SHIVS", "Statikk, chaining lightning down the wave"],
  ["SLOTS", "six of them, plus your boots"],
  ["SORCS", "sorcerer's shoes, for magic penetration"],
  ["SPEAR", "Spear of Shojin"],
  ["SPEED", "movement speed, and why boots matter"],
  ["STAFF", "Rabadon's, needlessly large"],
  ["STEEL", "as in plated steelcaps"],
  ["SWIFT", "the boots for when you just want to be elsewhere"],
  ["SWORD", "long sword, 350 gold"],
  ["TEARS", "Tear of the Goddess, stacking quietly"],
  ["THORN", "as in Thornmail, for the healers"],
  ["TITAN", "as in Titanic Hydra"],
  ["TOMES", "amplifying, 400 gold each"],
  ["TOOTH", "Nashor's, for attack speed and magic"],
  ["WANDS", "blasting, 850 gold"],
  ["ZEKES", "Zeke's Convergence, for the frontline"],

  /* --- Abilities and crowd control ----------------------- */
  ["ARROW", "Ashe's, from the other side of the map"],
  ["AUTOS", "the attacks in between the spells"],
  ["BLIND", "a blind pick, or Teemo's dart"],
  ["BLINK", "what flash actually does"],
  ["BOXES", "Shaco's, waiting in the dark"],
  ["CAGES", "Jarvan's ultimate, closing in"],
  ["CHARM", "Ahri's kiss, and the walk that follows"],
  ["CHIME", "Bard's, collected on the way past"],
  ["CLONE", "Shaco, LeBlanc, Neeko and Wukong"],
  ["CROWD", "as in crowd control — the CC in the chat"],
  ["CURSE", "Amumu's, of the Sad Mummy"],
  ["DECOY", "the one you chased instead of the champion"],
  ["DRAIN", "the health that leaves you and arrives elsewhere"],
  ["FEARS", "Fiddlesticks, in the fog"],
  ["HEALS", "Soraka, doing her job"],
  ["HOOKS", "Blitzcrank, Thresh, Pyke, Nautilus"],
  ["KNOCK", "the knock up Yasuo has been waiting for"],
  ["LOTUS", "Jhin's traps, and Katarina's death"],
  ["MEEPS", "Bard's little helpers"],
  ["MIMIC", "Sylas, using your ultimate better than you did"],
  ["PARRY", "Fiora's riposte, Jax's counter"],
  ["QUEST", "Kayle's, Nasus's, and the one on your support item"],
  ["QUICK", "as in quick cast"],
  ["ROOTS", "you can act, you cannot move"],
  ["SEEDS", "Zyra's, waiting in the grass"],
  ["SHOTS", "Jhin has four"],
  ["SHRED", "the armour, reduced"],
  ["SKILL", "as in skillshot"],
  ["SLEEP", "Zoe's bubble, and Lillia's lullaby"],
  ["SLOWS", "your movement speed, ruined"],
  ["SMART", "smartcast, and never look back"],
  ["SNARE", "a root, by another name"],
  ["SPELL", "Q, W, E and R"],
  ["SPINS", "Garen, Master Yi, and Katarina"],
  ["STUNS", "you can neither act nor move"],
  ["TAUNT", "Shen and Rammus say hello"],
  ["TRAPS", "Teemo's shrooms, Jhin's lotus, Caitlyn's nets"],
  ["ULTED", "hit by an ultimate, decisively"],
  ["WINDS", "Yasuo's wall of them"],

  /* --- Playing the game ---------------------------------- */
  ["BACKS", "recall, and the six seconds of hoping"],
  ["BAITS", "bait the ultimate, then fight"],
  ["BOOST", "the movement speed you badly needed"],
  ["BURST", "dead before the health bar moves"],
  ["CARRY", "what you promised in champion select"],
  ["CATCH", "caught out, alone, in the dark"],
  ["CHASE", "the thing that gets you killed under tower"],
  ["CHEAT", "the cheater recall, after a slow push"],
  ["CHUNK", "half your health, one combo"],
  ["CLEAR", "the wave, or the jungle, or both"],
  ["CLICK", "right click to move, mostly"],
  ["COMBO", "the sequence you practise in the practice tool"],
  ["CRASH", "send the wave into their tower"],
  ["DIVER", "goes in first, dies first"],
  ["DIVES", "the tower dive, and its consequences"],
  ["DUELS", "one against one, mid lane, now"],
  ["DUNKS", "Darius, arriving"],
  ["FARMS", "last hitting, patiently"],
  ["FEEDS", "kills, given away"],
  ["FIGHT", "the teamfight, eventually"],
  ["FLANK", "come from the side, not the front"],
  ["FOCUS", "focus the carry, please"],
  ["FRONT", "the line your tank is meant to hold"],
  ["GANKS", "the jungler, arriving"],
  ["GROUP", "group mid — the oldest plan there is"],
  ["JUKES", "into the bush, out of the bush"],
  ["KITED", "hit, step back, hit again"],
  ["LATER", "just farm, and we win later"],
  ["LEASH", "the favour you ask for at level one"],
  ["LEVEL", "six, and everything changes"],
  ["MACRO", "the game above the fighting"],
  ["MAGES", "the ones with the big numbers"],
  ["MARKS", "as in marksman"],
  ["MELEE", "you have to walk there"],
  ["MICRO", "the fighting itself"],
  ["PEELS", "keeping the carry alive"],
  ["PENTA", "five kills, one player, one life"],
  ["POKES", "chip damage, from a safe distance"],
  ["PORTS", "teleport, when you are needed elsewhere"],
  ["POWER", "the spike you have been waiting for"],
  ["PROCS", "the on-hit effect, triggering"],
  ["PROXY", "farming waves behind their tower"],
  ["RANGE", "you do not have to walk there"],
  ["RESET", "Katarina's entire personality"],
  ["ROAMS", "mid leaves lane, someone dies"],
  ["ROLES", "top, jungle, mid, bot, support"],
  ["SCALE", "weak early, terrifying late"],
  ["SCOUT", "look before you commit"],
  ["SETUP", "the vision, laid before the objective"],
  ["SHARD", "the small rune choices at the bottom"],
  ["SHOVE", "push the wave in fast"],
  ["SIEGE", "poke, wait, take the tower"],
  ["SIGHT", "what a ward buys you"],
  ["SNEAK", "Evelynn, Twitch and Rengar, arriving unseen"],
  ["SNIPE", "the execute from across the map"],
  ["SOLOS", "one against one, no help coming"],
  ["SPIKE", "the level or item where you get strong"],
  ["SPLIT", "push a side lane, take the map"],
  ["STACK", "Nasus, Veigar and Sion, patiently"],
  ["STALL", "hold on until late game"],
  ["STEAL", "the smite that ends friendships"],
  ["STOMP", "a very one-sided game"],
  ["SWAPS", "the lane swap, an old idea"],
  ["SWEEP", "the red trinket, hunting wards"],
  ["TANKS", "the ones who walk in first"],
  ["TEAMS", "five each, in theory"],
  ["THROW", "a won game, given away"],
  ["TIMER", "the one you should have set on Baron"],
  ["TRADE", "hit them more than they hit you"],
  ["WARDS", "vision, or the lack of it"],
  ["WHIFF", "the skillshot that missed"],
  ["WOMBO", "the combo, all at once"],
  ["ZONED", "kept off the farm you needed"],

  /* --- The announcer and the scoreboard ------------------ */
  ["BLOOD", "first blood, and the gold that comes with it"],
  ["DEATH", "the timer that gets longer every time"],
  ["ENEMY", "the announcer's favourite word"],
  ["KILLS", "the K in KDA"],
  ["RATIO", "the K, the D and the A"],
  ["SCORE", "the tab screen, checked far too often"],
  ["SLAIN", "an enemy has been slain"],
  ["SPREE", "a killing spree, and rising"],
  ["STATS", "everything the tab screen will tell you"],
  ["VOTES", "the surrender vote, at nineteen minutes"],

  /* --- Around the game ----------------------------------- */
  ["ARENA", "the 2v2v2v2 mode"],
  ["ARURF", "all random, ultra rapid fire"],
  ["BANDS", "KDA, Pentakill, True Damage, Heartsteel"],
  ["BRAWL", "the newer all-out lane mode"],
  ["CHAMP", "short for champion, obviously"],
  ["CHEST", "hextech, and only if you earn it"],
  ["CLASH", "the weekend tournament mode"],
  ["CLIMB", "up the ladder, one game at a time"],
  ["CLIPS", "the ten seconds you will send to everyone"],
  ["CRAFT", "disenchant, then make what you actually wanted"],
  ["DECAY", "rank decay, for the ones who stopped playing"],
  ["DODGE", "sometimes the best move in champ select"],
  ["DRAFT", "picks, bans and second thoughts"],
  ["EMOTE", "the mastery emote, right after the kill"],
  ["EVENT", "a pass, a shop, and a deadline"],
  ["FILLS", "the role you did not want"],
  ["GAMES", "just one more, at half past midnight"],
  ["GRIND", "the climb, in its least romantic form"],
  ["HOURS", "the ones this game has quietly taken"],
  ["ICONS", "the little picture beside your name"],
  ["LOBBY", "champion select, before the storm"],
  ["MAINS", "the one champion you actually know"],
  ["MATCH", "matchmaking, and the queue behind it"],
  ["METAS", "the best builds, until next patch"],
  ["MOBAS", "the genre this game defined"],
  ["MUSIC", "the champ select theme, and Pentakill"],
  ["NERFS", "the patch note you did not want"],
  ["NORMS", "normal games, where nothing counts"],
  ["NOTES", "the patch ones, read with dread"],
  ["PAGES", "rune pages, saved and never updated"],
  ["PATCH", "the reason your main is bad now"],
  ["PICKS", "champion select, in a word"],
  ["POOLS", "your champion pool, narrower than you think"],
  ["PROMO", "the series standing between you and the next rank"],
  ["QUEUE", "where you wait, and then dodge"],
  ["RANKS", "iron all the way up to challenger"],
  ["READY", "the check nobody presses in time"],
  ["RUNES", "the page you forgot to set"],
  ["SCRIM", "practice, against another team"],
  ["SHOPS", "the fountain one, opened with P"],
  ["SKINS", "the real endgame"],
  ["SUMMS", "your summoner spells — both on cooldown"],
  ["SWARM", "the co-op survival mode"],
  ["TOKEN", "earned in an event, spent in its shop"],
  ["TRICK", "the one-trick, and very good at it"],
  ["VOICE", "the lines you can quote from memory"],

  /* --- Skin universes ------------------------------------ */
  ["ANIMA", "Anima Squad, saving the world in pastel"],
  ["COVEN", "the skin line, all candles and dread"],
  ["LUNAR", "the new year skins, every year"],
  ["PARTY", "pool party, every summer"],
  ["PULSE", "as in Pulsefire, straight from the future"],

  /* --- The community ------------------------------------- */
  ["AFKED", "someone left; it is four against five"],
  ["DIFFS", "jungle diff, mid diff, and so on"],
  ["FLAME", "what happens in all chat"],
  ["GRIEF", "the report-worthy kind"],
  ["HONOR", "the thing you get for being pleasant"],
  ["INTED", "the game, thrown, on purpose or otherwise"],
  ["MUTED", "all chat, mercifully"],
  ["SMURF", "a very good player in a very low game"],
  ["SORRY", "typed in all chat, occasionally sincere"],
  ["TOXIC", "the chat, and the reason mute exists"],

  /* --- Esports ------------------------------------------- */
  ["BENGI", "the jungler behind a dynasty"],
  ["CHOVY", "one of the LCK's finest"],
  ["COACH", "the one shouting behind the players"],
  ["FAKER", "the greatest to ever play"],
  ["FINAL", "the one played in front of a stadium"],
  ["INSEC", "the kick that got its own verb"],
  ["KERIA", "a support who plays like a carry"],
  ["PERKZ", "Europe's loudest mid laner"],
  ["ROGUE", "Akali's title, and a European team"],
  ["RULER", "a marksman with the trophies to prove it"],
  ["VIPER", "a marksman, and a very good one"],
  ["XPEKE", "the backdoor that made a career"]
];

export const ANSWERS = WORDS.map(w => w[0]);
export const GLOSS = Object.fromEntries(WORDS);
